// Banco de preguntas semilla — contenido original inspirado en el temario
// publico del Reglamento General de Circulacion y las senales oficiales
// espanolas. Es un punto de partida para desarrollo/demo: antes de usarlo
// para preparar un examen real, conviene que lo revise y amplie alguien con
// conocimiento actualizado del temario (las normas cambian con el tiempo).

export interface SeedQuestion {
  category: string; // slug
  text: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  isSerious?: boolean;
}

export const categories = [
  { slug: "senales", name: "Señales de tráfico" },
  { slug: "prioridad", name: "Prioridad y circulación" },
  { slug: "velocidad", name: "Velocidad y distancias" },
  { slug: "alcohol-drogas", name: "Alcohol, drogas y fatiga" },
  { slug: "mecanica-documentos", name: "Mecánica y documentación" },
  { slug: "seguridad-vial", name: "Seguridad vial y primeros auxilios" },
];

export const questions: SeedQuestion[] = [
  // ---- SEÑALES ----
  {
    category: "senales",
    text: "Una señal circular con fondo blanco, borde rojo y una figura negra en el centro indica:",
    options: ["Una prohibición o restricción", "Una obligación", "Una indicación general", "Un peligro"],
    correctIndex: 0,
    explanation: "Las señales circulares de borde rojo son de prohibición o restricción de acceso o circulación.",
  },
  {
    category: "senales",
    text: "Las señales de forma triangular con borde rojo advierten de:",
    options: ["Un peligro próximo", "Una prohibición", "Una obligación", "Un servicio disponible"],
    correctIndex: 0,
    explanation: "El triángulo de borde rojo es la forma reservada para las señales de peligro (P).",
  },
  {
    category: "senales",
    text: "Una señal circular de fondo azul con una flecha blanca indica:",
    options: ["Sentido obligatorio a seguir", "Sentido prohibido", "Dirección aconsejada", "Fin de una prohibición"],
    correctIndex: 0,
    explanation: "El azul en señales circulares se usa para señales de obligación, como el sentido obligatorio.",
  },
  {
    category: "senales",
    text: "¿Qué significa una señal cuadrada o rectangular de fondo azul?",
    options: ["Indicación general (información, servicios, orientación)", "Prohibición", "Peligro", "Obligación de detenerse"],
    correctIndex: 0,
    explanation: "El formato rectangular/cuadrado azul se reserva a señales de indicación.",
  },
  {
    category: "senales",
    text: "La señal de STOP obliga a:",
    options: [
      "Detener el vehículo completamente y ceder el paso antes de continuar",
      "Reducir la velocidad sin necesidad de parar",
      "Detenerse solo si hay otros vehículos",
      "Ceder el paso sin necesidad de detenerse",
    ],
    correctIndex: 0,
    explanation: "STOP exige parada total, aunque no se vean vehículos, y ceder el paso antes de reanudar la marcha.",
  },
  {
    category: "senales",
    text: "Una señal triangular invertida (con el vértice hacia abajo) representa:",
    options: ["Ceda el paso", "Stop", "Dirección prohibida", "Intersección con prioridad"],
    correctIndex: 0,
    explanation: "El triángulo invertido es exclusivo de la señal de Ceda el Paso.",
  },
  {
    category: "senales",
    text: "Cuando una señal fija de circulación entra en contradicción con las órdenes de un agente, ¿cuál prevalece?",
    options: ["Las órdenes del agente", "La señal fija", "Ninguna, se debe parar", "La más restrictiva de las dos"],
    correctIndex: 0,
    explanation: "Las indicaciones de los agentes prevalecen sobre cualquier otra señal, semáforo o norma de circulación.",
  },
  {
    category: "senales",
    text: "Un semáforo en ámbar (amarillo) fijo significa:",
    options: [
      "Detenerse, salvo que al encenderse esté tan próximo que no pueda parar con seguridad",
      "Pasar con precaución",
      "Ceder el paso solo a peatones",
      "Vía libre igual que el verde",
    ],
    correctIndex: 0,
    explanation: "El ámbar obliga a detenerse salvo que el frenado brusco pudiera resultar peligroso.",
  },
  {
    category: "senales",
    text: "Las marcas viales de color amarillo en el bordillo o el pavimento normalmente indican:",
    options: ["Restricciones de parada o estacionamiento", "Carril reservado a bicicletas", "Zona de adelantamiento permitido", "Carril de velocidad reducida"],
    correctIndex: 0,
    explanation: "El amarillo en marcas viales suele señalar limitaciones de parada/estacionamiento (p. ej. vado, zona de carga).",
  },
  {
    category: "senales",
    text: "Una línea continua en el eje de la calzada significa que:",
    options: ["Está prohibido cruzarla o circular sobre ella para adelantar", "Se puede cruzar si no viene nadie", "Solo la pueden cruzar los autobuses", "Indica el borde de la calzada"],
    correctIndex: 0,
    explanation: "La línea continua prohíbe cruzarla, incluso para adelantamientos, salvo excepciones muy concretas (obstáculos, etc.).",
  },

  // ---- PRIORIDAD ----
  {
    category: "prioridad",
    text: "En una intersección sin señales de prioridad, ¿quién tiene preferencia?",
    options: ["El vehículo que llega por la derecha", "El vehículo más grande", "El que circula más rápido", "El primero que toque el claxon"],
    correctIndex: 0,
    explanation: "A falta de señalización, rige la regla de prioridad de paso por la derecha.",
  },
  {
    category: "prioridad",
    text: "En una rotonda, la prioridad general es para:",
    options: ["Los vehículos que ya circulan dentro de la rotonda", "Los vehículos que van a entrar", "El vehículo más grande", "El que entra por la izquierda"],
    correctIndex: 0,
    explanation: "Quien circula dentro de la rotonda tiene prioridad sobre quien pretende incorporarse.",
  },
  {
    category: "prioridad",
    text: "¿Cuándo se debe ceder el paso a un vehículo de emergencia con señales luminosas y acústicas activadas?",
    options: ["Siempre, facilitándole el paso lo antes posible y de forma segura", "Solo si viene por detrás", "Solo en autovías", "Nunca, ellos deben adaptarse al tráfico"],
    correctIndex: 0,
    explanation: "Los vehículos prioritarios en servicio de urgencia tienen preferencia de paso; el resto debe facilitarles la circulación.",
  },
  {
    category: "prioridad",
    text: "Al incorporarse a una vía desde un carril de aceleración, el conductor debe:",
    options: ["Ceder el paso a los vehículos que ya circulan por la vía principal", "Tener siempre prioridad", "Detenerse obligatoriamente antes de incorporarse", "Adelantar antes de incorporarse"],
    correctIndex: 0,
    explanation: "Quien se incorpora desde un carril de aceleración debe ceder el paso a quienes ya circulan por la vía.",
  },
  {
    category: "prioridad",
    text: "En un cruce con un peatón cruzando por un paso señalizado sin semáforo, el conductor debe:",
    options: ["Detenerse y dejarle cruzar", "Tocar el claxon para que se dé prisa", "Pasar si el peatón aún no ha bajado del todo a la calzada", "Adelantarlo por detrás"],
    correctIndex: 0,
    explanation: "Los peatones tienen prioridad en los pasos de peatones señalizados; el conductor debe detenerse.",
  },
  {
    category: "prioridad",
    text: "Dos vehículos llegan a la vez a una intersección sin señalizar, uno de frente y otro girando a la izquierda desde el sentido contrario. ¿Quién tiene prioridad?",
    options: ["El vehículo que circula de frente", "El que gira a la izquierda", "Ninguno, deben parar ambos indefinidamente", "El vehículo más nuevo"],
    correctIndex: 0,
    explanation: "El vehículo que gira debe ceder el paso al que circula de frente en sentido contrario.",
  },
  {
    category: "prioridad",
    text: "¿Qué indica una señal de 'Intersección con prioridad'?",
    options: ["Que la vía por la que se circula tiene prioridad sobre las que se crucen", "Que hay que ceder el paso en el próximo cruce", "Que se aproxima una rotonda", "Que la vía se va a estrechar"],
    correctIndex: 0,
    explanation: "Esta señal informa de que se mantiene la prioridad de paso en los cruces sucesivos hasta que se indique lo contrario.",
  },
  {
    category: "prioridad",
    text: "En un tramo de carretera estrecho donde solo cabe un vehículo, si se cruzan un turismo y un camión, ¿quién debe ceder normalmente el paso?",
    options: ["El vehículo que tenga más facilidad para maniobrar o retroceder con seguridad", "Siempre el turismo", "Siempre el camión", "El que vaya más rápido"],
    correctIndex: 0,
    explanation: "Ante un obstáculo o paso estrecho, cede quien pueda hacerlo con mayor facilidad y seguridad, aunque hay reglas específicas según el desnivel o el tipo de vía.",
  },
  {
    category: "prioridad",
    text: "Circulando por una vía y queriendo girar a la derecha, cruzándose con un ciclista que sigue recto por el carril bici, el conductor debe:",
    options: ["Ceder el paso al ciclista antes de girar", "Girar primero porque va en la misma dirección", "Adelantar al ciclista justo antes del giro", "Tocar el claxon para que frene"],
    correctIndex: 0,
    explanation: "El vehículo que gira debe ceder el paso a los ciclistas que continúan de frente por su carril.",
  },
  {
    category: "prioridad",
    text: "¿Qué se debe hacer al aproximarse a un paso a nivel sin barreras con la señal de STOP?",
    options: ["Detenerse, mirar y escuchar antes de cruzar", "Cruzar rápido para no quedarse atrapado", "Solo reducir la velocidad", "Tocar el claxon y cruzar"],
    correctIndex: 0,
    explanation: "En pasos a nivel sin barreras señalizados con STOP es obligatorio detenerse y verificar que no se aproxima ningún tren.",
  },

  // ---- VELOCIDAD ----
  {
    category: "velocidad",
    text: "En una vía urbana, sin otra señalización, la velocidad genérica máxima suele ser:",
    options: ["50 km/h", "70 km/h", "90 km/h", "30 km/h en todos los casos"],
    correctIndex: 0,
    explanation: "La velocidad genérica en vías urbanas de un solo carril por sentido es de 50 km/h salvo señalización distinta (hay calles a 20 o 30 según el tipo de vía).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "La distancia de seguridad con el vehículo de delante debe permitir:",
    options: ["Detenerse a tiempo si este frena bruscamente", "Adelantarlo en cualquier momento", "Ver la matrícula del vehículo de delante", "Tocar el claxon si se acerca demasiado"],
    correctIndex: 0,
    explanation: "La distancia de seguridad debe ser suficiente para poder parar sin colisionar si el vehículo precedente frena.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "Circular a una velocidad excesiva para las condiciones de la vía (lluvia, niebla, curvas) aunque no se supere el límite señalizado es:",
    options: ["Una infracción, porque la velocidad debe adaptarse a las circunstancias", "Correcto siempre que no se supere el límite", "Solo sancionable de noche", "Solo aplicable a camiones"],
    correctIndex: 0,
    explanation: "El límite señalizado es un máximo; siempre debe adaptarse la velocidad a las condiciones reales (visibilidad, tráfico, firme, etc.).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "El exceso de velocidad reduce sobre todo:",
    options: ["El tiempo de reacción disponible y aumenta la distancia de frenado", "Únicamente el consumo de combustible", "El desgaste de los neumáticos, sin más efectos", "Solamente la comodidad del viaje"],
    correctIndex: 0,
    explanation: "A mayor velocidad, mayor distancia recorrida durante el tiempo de reacción y mayor distancia de frenado (crece de forma cuadrática).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "En autopista o autovía, un turismo sin remolque circula, con carácter general, a una velocidad máxima de:",
    options: ["120 km/h", "100 km/h", "90 km/h", "140 km/h"],
    correctIndex: 0,
    explanation: "El límite genérico para turismos en autopista/autovía es 120 km/h, salvo señalización distinta.",
  },
  {
    category: "velocidad",
    text: "¿Qué es la 'huella de frenada'?",
    options: ["La marca dejada por los neumáticos al frenar bruscamente", "La distancia de seguridad recomendada", "El desgaste normal del neumático", "Una señal en el asfalto"],
    correctIndex: 0,
    explanation: "Es la marca visible en el pavimento que deja un neumático al bloquearse durante un frenazo intenso.",
  },
  {
    category: "velocidad",
    text: "Al circular en un túnel, respecto a la distancia con el vehículo de delante hay que:",
    options: ["Aumentar la precaución y mantener mayor distancia de seguridad", "Reducirla porque hay menos espacio", "Es indiferente", "Solo aplica si el túnel es muy largo"],
    correctIndex: 0,
    explanation: "En túneles se recomienda aumentar la distancia de seguridad por la menor visibilidad y mayor riesgo en caso de incidente.",
  },
  {
    category: "velocidad",
    text: "La 'regla de los dos segundos' se usa para:",
    options: ["Calcular una distancia de seguridad orientativa con el vehículo de delante", "Medir el tiempo de un adelantamiento", "Saber cuánto dura el ámbar de un semáforo", "Calcular el tiempo de frenada en mojado"],
    correctIndex: 0,
    explanation: "Consiste en dejar pasar al menos dos segundos entre que el vehículo de delante pasa por un punto y tú pasas por el mismo punto.",
  },
  {
    category: "velocidad",
    text: "En condiciones de lluvia, la distancia de seguridad respecto a la habitual debe:",
    options: ["Aumentarse, al menos duplicándola", "Mantenerse igual", "Reducirse porque se circula más despacio", "Da igual si se llevan neumáticos nuevos"],
    correctIndex: 0,
    explanation: "Con el firme mojado la adherencia disminuye y la distancia de frenado aumenta, por lo que conviene aumentar considerablemente la distancia de seguridad.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "Para un ciclomotor o motocicleta sin autorización especial, en general los límites de velocidad:",
    options: ["Se ajustan a las características técnicas del vehículo y a los límites de la vía", "Son siempre superiores a los de los turismos", "No existen en ninguna vía", "Solo aplican en ciudad"],
    correctIndex: 0,
    explanation: "Cada tipo de vehículo tiene límites específicos según sus características, además de respetar el límite general de la vía.",
  },

  // ---- ALCOHOL Y DROGAS ----
  {
    category: "alcohol-drogas",
    text: "El alcohol en el organismo afecta principalmente a:",
    options: ["El tiempo de reacción y la percepción del riesgo", "Solo a la vista nocturna", "Solo al sentido del oído", "Nada si se ha comido bien antes"],
    correctIndex: 0,
    explanation: "El alcohol ralentiza los reflejos, reduce la percepción del peligro y produce exceso de confianza.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Conducir bajo los efectos de bebidas alcohólicas por encima de las tasas legales es:",
    options: ["Una infracción grave o muy grave según la tasa, con posibles consecuencias penales", "Solo una recomendación a evitar", "Legal si se conduce despacio", "Solo sancionable de noche"],
    correctIndex: 0,
    explanation: "Superar las tasas de alcoholemia permitidas constituye infracción administrativa (y puede ser delito según la tasa) con sanciones económicas y de puntos.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "La fatiga y el sueño al volante:",
    options: ["Aumentan mucho el riesgo de accidente y deben evitarse descansando", "No afectan si se lleva la radio encendida", "Se solucionan abriendo la ventanilla", "Solo afectan en viajes de más de 1000 km"],
    correctIndex: 0,
    explanation: "El cansancio reduce la atención y los reflejos; la única solución eficaz es parar y descansar.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "El consumo de determinados medicamentos (ansiolíticos, antihistamínicos, etc.) antes de conducir:",
    options: ["Puede afectar a la capacidad de conducción y debe consultarse el prospecto", "Nunca afecta a la conducción", "Solo afecta si se toman de noche", "Mejora los reflejos"],
    correctIndex: 0,
    explanation: "Muchos medicamentos producen somnolencia o afectan a los reflejos; hay que revisar el prospecto y el pictograma correspondiente.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Tras consumir drogas, aunque sea en pequeña cantidad, para conducir:",
    options: ["Está prohibido conducir, hay tolerancia cero", "Se puede conducir si han pasado 2 horas", "Solo está prohibido de noche", "Depende del tipo de vehículo"],
    correctIndex: 0,
    explanation: "Para las drogas la legislación aplica tolerancia cero: cualquier resultado positivo es infracción.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "¿Qué efecto produce el alcohol sobre el campo visual?",
    options: ["Lo reduce, produciendo una especie de 'visión en túnel'", "Lo amplía notablemente", "No tiene ningún efecto", "Mejora la visión nocturna"],
    correctIndex: 0,
    explanation: "El alcohol reduce el campo visual periférico, dificultando detectar peligros laterales.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Un conductor novel (con menos de determinada experiencia) tiene, respecto al alcohol, tasas de alcoholemia permitidas:",
    options: ["Más restrictivas que un conductor experimentado", "Iguales que cualquier otro conductor", "Más permisivas", "No aplican tasas específicas"],
    correctIndex: 0,
    explanation: "Conductores noveles y profesionales suelen tener límites de alcoholemia más bajos que el resto.",
  },
  {
    category: "alcohol-drogas",
    text: "La negativa a someterse a las pruebas de detección de alcohol o drogas que ordene un agente es:",
    options: ["Un delito", "Una simple recomendación que se puede rechazar sin consecuencias", "Solo aplicable a profesionales", "Legal si el conductor no ha bebido"],
    correctIndex: 0,
    explanation: "Negarse a las pruebas de alcoholemia o drogas constituye delito, independientemente del resultado que se hubiera obtenido.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Beber café o ducharse tras haber consumido alcohol:",
    options: ["No elimina el alcohol del organismo más rápido, solo el tiempo lo hace", "Elimina el alcohol al instante", "Reduce la tasa de alcoholemia inmediatamente", "Hace que el etilómetro no detecte alcohol"],
    correctIndex: 0,
    explanation: "Solo el paso del tiempo elimina el alcohol de la sangre; no existen remedios caseros eficaces.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "El alcohol favorece especialmente la sensación de:",
    options: ["Exceso de confianza y subestimación del riesgo", "Mayor prudencia al volante", "Mejora de los reflejos", "Mayor concentración"],
    correctIndex: 0,
    explanation: "Uno de los efectos más peligrosos del alcohol es que genera una falsa sensación de seguridad y minimiza la percepción del riesgo.",
    isSerious: true,
  },

  // ---- MECANICA Y DOCUMENTACION ----
  {
    category: "mecanica-documentos",
    text: "La profundidad mínima legal del dibujo de los neumáticos en un turismo es de:",
    options: ["1,6 mm", "3 mm", "0,5 mm", "5 mm"],
    correctIndex: 0,
    explanation: "El mínimo legal en la Unión Europea para turismos es 1,6 mm de profundidad en el dibujo principal.",
  },
  {
    category: "mecanica-documentos",
    text: "¿Qué documento acredita que un vehículo ha superado los controles técnicos periódicos?",
    options: ["El certificado/pegatina de la ITV en vigor", "El permiso de circulación", "La ficha técnica original", "El seguro obligatorio"],
    correctIndex: 0,
    explanation: "La ITV (Inspección Técnica de Vehículos) certifica que el vehículo cumple las condiciones técnicas de seguridad y medioambientales.",
  },
  {
    category: "mecanica-documentos",
    text: "Circular sin el seguro obligatorio en vigor es:",
    options: ["Una infracción muy grave", "Una infracción leve", "Legal si el vehículo es muy nuevo", "Solo se sanciona si hay accidente"],
    correctIndex: 0,
    explanation: "Circular sin seguro obligatorio se considera infracción muy grave, con independencia de que se produzca o no un siniestro.",
  },
  {
    category: "mecanica-documentos",
    text: "Si durante la marcha se enciende el testigo rojo de presión de aceite, se debe:",
    options: ["Detener el vehículo lo antes posible con seguridad y revisar el nivel", "Seguir circulando con normalidad", "Aumentar la velocidad para llegar antes al taller", "Apagar y encender el motor para que se apague el testigo"],
    correctIndex: 0,
    explanation: "El testigo rojo de aceite indica un fallo grave de lubricación; continuar circulando puede dañar seriamente el motor.",
  },
  {
    category: "mecanica-documentos",
    text: "La presión de los neumáticos inferior a la recomendada por el fabricante provoca:",
    options: ["Mayor desgaste, peor adherencia y mayor consumo", "Mejor adherencia en curva", "Menor consumo de combustible", "Ningún efecto relevante"],
    correctIndex: 0,
    explanation: "Una presión insuficiente aumenta la superficie de contacto de forma irregular, deteriora el neumático y empeora el comportamiento del vehículo.",
  },
  {
    category: "mecanica-documentos",
    text: "El líquido de frenos debe revisarse porque:",
    options: ["Con el tiempo absorbe humedad y pierde eficacia", "Nunca necesita revisión", "Se debe cambiar solo si cambia de color", "Solo afecta a vehículos diésel"],
    correctIndex: 0,
    explanation: "El líquido de frenos es higroscópico (absorbe agua), lo que reduce su punto de ebullición y la eficacia de frenada; se recomienda cambiarlo periódicamente.",
  },
  {
    category: "mecanica-documentos",
    text: "¿Qué es el permiso de circulación?",
    options: ["El documento administrativo que autoriza a un vehículo a circular", "El carné de conducir del titular", "El justificante del seguro", "El resultado de la ITV"],
    correctIndex: 0,
    explanation: "El permiso de circulación es el documento que matricula y autoriza la circulación de un vehículo concreto.",
  },
  {
    category: "mecanica-documentos",
    text: "Un chaleco reflectante y los triángulos de preseñalización deben usarse:",
    options: ["Al detenerse en el arcén por avería o accidente, para señalizar y ser visible", "Solo de noche", "Solo en autopistas de peaje", "Únicamente si lo pide un agente"],
    correctIndex: 0,
    explanation: "Es obligatorio colocarse el chaleco antes de bajar del vehículo detenido en el arcén y señalizar con los triángulos (o la V16 si aplica) para avisar a otros conductores.",
  },
  {
    category: "mecanica-documentos",
    text: "¿Con qué frecuencia general debe pasar la ITV un turismo nuevo?",
    options: ["A partir de cierta antigüedad, con periodicidad creciente (p. ej. tras 4 años, luego cada 2, luego cada año)", "Nunca, si es nuevo", "Cada mes", "Solo si ha tenido un accidente"],
    correctIndex: 0,
    explanation: "Los turismos suelen pasar la primera ITV a los 4 años, luego cada 2 años, y anualmente al superar cierta antigüedad (los plazos exactos pueden variar por normativa).",
  },
  {
    category: "mecanica-documentos",
    text: "Si el consumo de combustible aumenta de forma anómala sin motivo aparente, puede deberse a:",
    options: ["Un mal ajuste del motor, neumáticos deshinchados o filtros sucios, entre otras causas", "Nunca a un problema mecánico", "Siempre a la calidad del combustible", "Al color del vehículo"],
    correctIndex: 0,
    explanation: "Un aumento anómalo del consumo suele indicar un problema mecánico (motor, neumáticos, filtros) que conviene revisar.",
  },

  // ---- SEGURIDAD VIAL Y PRIMEROS AUXILIOS ----
  {
    category: "seguridad-vial",
    text: "Ante un accidente de tráfico, la primera actuación del primer interviniente debe ser:",
    options: ["Proteger la zona para evitar más accidentes (señalizar, balizar)", "Mover a los heridos inmediatamente", "Llamar primero a la familia de los heridos", "Retirar los vehículos de la calzada de inmediato en todos los casos"],
    correctIndex: 0,
    explanation: "La secuencia PAS (Proteger, Avisar, Socorrer) empieza siempre por proteger el lugar del accidente.",
  },
  {
    category: "seguridad-vial",
    text: "Al llamar al 112 tras un accidente, es importante indicar:",
    options: ["Ubicación exacta, número de heridos y su estado aparente", "Solo la matrícula de los vehículos", "El nombre del seguro", "Nada, ellos ya lo saben todo"],
    correctIndex: 0,
    explanation: "Dar una ubicación precisa y describir el número y estado de los heridos ayuda a movilizar los recursos adecuados.",
  },
  {
    category: "seguridad-vial",
    text: "¿Se debe quitar el casco a un motorista herido tras un accidente?",
    options: ["Solo si es imprescindible para reanimarlo y por personal con la técnica adecuada", "Sí, siempre y lo antes posible", "Nunca bajo ninguna circunstancia", "Solo si el motorista lo pide"],
    correctIndex: 0,
    explanation: "Retirar el casco de forma incorrecta puede agravar lesiones cervicales; solo se retira si es necesario para reanimación y con la técnica adecuada.",
  },
  {
    category: "seguridad-vial",
    text: "El cinturón de seguridad debe usarse:",
    options: ["Siempre, tanto en plazas delanteras como traseras cuando exista", "Solo en autopista", "Solo por el conductor", "Solo en trayectos largos"],
    correctIndex: 0,
    explanation: "El cinturón es obligatorio para todos los ocupantes en todas las plazas equipadas con él, en cualquier vía.",
  },
  {
    category: "seguridad-vial",
    text: "Los sistemas de retención infantil (sillitas) deben usarse:",
    options: ["Según la talla/peso del menor, según lo indicado por la normativa vigente", "Solo si el niño lo pide", "Solo en viajes largos", "Nunca en el asiento delantero bajo ninguna circunstancia"],
    correctIndex: 0,
    explanation: "La normativa exige el uso de sistemas de retención adaptados a la talla y peso del menor hasta cierta estatura/edad.",
  },
  {
    category: "seguridad-vial",
    text: "Ante un vehículo averiado en el arcén, antes de bajarse del coche los ocupantes deben:",
    options: ["Ponerse el chaleco reflectante", "Encender las luces largas", "Bajar todos a la vez por el lado de la calzada", "Abrir todas las puertas"],
    correctIndex: 0,
    explanation: "Es obligatorio colocarse el chaleco reflectante antes de salir del vehículo detenido en el arcén o calzada.",
  },
  {
    category: "seguridad-vial",
    text: "El uso del teléfono móvil sujeto con la mano mientras se conduce es:",
    options: ["Una infracción grave, aunque sea en un semáforo en rojo", "Legal si el vehículo está parado en un semáforo", "Legal siempre que sea una llamada corta", "Solo se sanciona de noche"],
    correctIndex: 0,
    explanation: "Usar el móvil sujeto con la mano mientras se conduce está prohibido y es infracción grave, incluso detenido en un semáforo si el motor no está apagado.",
  },
  {
    category: "seguridad-vial",
    text: "En caso de vuelco o incendio de un vehículo con ocupantes atrapados y en peligro inminente, ¿se puede mover a un herido?",
    options: ["Sí, solo si existe un peligro inminente y no hay otra alternativa", "Nunca, bajo ninguna circunstancia", "Sí, siempre que sea posible aunque no haya peligro", "Solo si lo autoriza un médico por teléfono"],
    correctIndex: 0,
    explanation: "La norma general es no mover a un herido, salvo peligro inminente (incendio, riesgo de nuevo atropello, etc.) en que no quede otra opción.",
  },
  {
    category: "seguridad-vial",
    text: "El punto ciego de un vehículo es:",
    options: ["La zona alrededor del vehículo que no se ve por los retrovisores ni directamente", "Una avería del sistema de luces", "La parte del parabrisas sucia", "El área delante del capó"],
    correctIndex: 0,
    explanation: "Son zonas, especialmente a los laterales traseros, donde otros vehículos pueden quedar ocultos a la vista del conductor.",
  },
  {
    category: "seguridad-vial",
    text: "El dispositivo V16 conectado (baliza luminosa) se utiliza para:",
    options: ["Señalizar un vehículo detenido o en peligro sin necesidad de bajarse a colocar triángulos", "Sustituir al seguro obligatorio", "Indicar cambio de carril", "Iluminar la calzada de noche en sustitución de las luces"],
    correctIndex: 0,
    explanation: "La baliza V16 conectada permite señalizar la posición del vehículo de forma visible sin exponer al conductor al bajarse en la calzada.",
  },
];
