// Banco de preguntas semilla — contenido original inspirado en el temario
// publico del Reglamento General de Circulacion y las senales oficiales
// espanolas. Es un punto de partida para desarrollo/demo: antes de usarlo
// para preparar un examen real, conviene que lo revise y amplie alguien con
// conocimiento actualizado del temario (las normas cambian con el tiempo).

export interface SeedQuestion {
  category: string; // slug
  text: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  isSerious?: boolean;
}

export const categories = [
  { slug: "senales", name: "Señales de tráfico" },
  { slug: "prioridad", name: "Prioridad y circulación" },
  { slug: "velocidad", name: "Velocidad y distancias" },
  { slug: "adelantamiento", name: "Adelantamientos" },
  { slug: "parada-estacionamiento", name: "Parada y estacionamiento" },
  { slug: "luces", name: "Luces y alumbrado" },
  { slug: "alcohol-drogas", name: "Alcohol, drogas y fatiga" },
  { slug: "sanciones-puntos", name: "Sanciones y puntos del carné" },
  { slug: "mecanica-documentos", name: "Mecánica y documentación" },
  { slug: "menores-transporte", name: "Menores y transporte de personas" },
  { slug: "medio-ambiente", name: "Medio ambiente y conducción eficiente" },
  { slug: "autopistas-vias-especiales", name: "Autopistas, autovías y vías especiales" },
  { slug: "seguridad-vial", name: "Seguridad vial y primeros auxilios" },
];

export const questions: SeedQuestion[] = [
  // ---- SEÑALES ----
  {
    category: "senales",
    text: "Una señal circular con fondo blanco, borde rojo y una figura negra en el centro indica:",
    options: ["Una prohibición o restricción", "Una obligación", "Una indicación general", "Un peligro"],
    correctIndex: 0,
    explanation: "Las señales circulares de borde rojo son de prohibición o restricción de acceso o circulación.",
  },
  {
    category: "senales",
    text: "Las señales de forma triangular con borde rojo advierten de:",
    options: ["Un peligro próximo", "Una prohibición", "Una obligación", "Un servicio disponible"],
    correctIndex: 0,
    explanation: "El triángulo de borde rojo es la forma reservada para las señales de peligro (P).",
  },
  {
    category: "senales",
    text: "Una señal circular de fondo azul con una flecha blanca indica:",
    options: ["Sentido obligatorio a seguir", "Sentido prohibido", "Dirección aconsejada", "Fin de una prohibición"],
    correctIndex: 0,
    explanation: "El azul en señales circulares se usa para señales de obligación, como el sentido obligatorio.",
  },
  {
    category: "senales",
    text: "¿Qué significa una señal cuadrada o rectangular de fondo azul?",
    options: ["Indicación general (información, servicios, orientación)", "Prohibición", "Peligro", "Obligación de detenerse"],
    correctIndex: 0,
    explanation: "El formato rectangular/cuadrado azul se reserva a señales de indicación.",
  },
  {
    category: "senales",
    text: "La señal de STOP obliga a:",
    options: [
      "Detener el vehículo completamente y ceder el paso antes de continuar",
      "Reducir la velocidad sin necesidad de parar",
      "Detenerse solo si hay otros vehículos",
      "Ceder el paso sin necesidad de detenerse",
    ],
    correctIndex: 0,
    explanation: "STOP exige parada total, aunque no se vean vehículos, y ceder el paso antes de reanudar la marcha.",
  },
  {
    category: "senales",
    text: "Una señal triangular invertida (con el vértice hacia abajo) representa:",
    options: ["Ceda el paso", "Stop", "Dirección prohibida", "Intersección con prioridad"],
    correctIndex: 0,
    explanation: "El triángulo invertido es exclusivo de la señal de Ceda el Paso.",
  },
  {
    category: "senales",
    text: "Cuando una señal fija de circulación entra en contradicción con las órdenes de un agente, ¿cuál prevalece?",
    options: ["Las órdenes del agente", "La señal fija", "Ninguna, se debe parar", "La más restrictiva de las dos"],
    correctIndex: 0,
    explanation: "Las indicaciones de los agentes prevalecen sobre cualquier otra señal, semáforo o norma de circulación.",
  },
  {
    category: "senales",
    text: "Un semáforo en ámbar (amarillo) fijo significa:",
    options: [
      "Detenerse, salvo que al encenderse esté tan próximo que no pueda parar con seguridad",
      "Pasar con precaución",
      "Ceder el paso solo a peatones",
      "Vía libre igual que el verde",
    ],
    correctIndex: 0,
    explanation: "El ámbar obliga a detenerse salvo que el frenado brusco pudiera resultar peligroso.",
  },
  {
    category: "senales",
    text: "Las marcas viales de color amarillo en el bordillo o el pavimento normalmente indican:",
    options: ["Restricciones de parada o estacionamiento", "Carril reservado a bicicletas", "Zona de adelantamiento permitido", "Carril de velocidad reducida"],
    correctIndex: 0,
    explanation: "El amarillo en marcas viales suele señalar limitaciones de parada/estacionamiento (p. ej. vado, zona de carga).",
  },
  {
    category: "senales",
    text: "Una línea continua en el eje de la calzada significa que:",
    options: ["Está prohibido cruzarla o circular sobre ella para adelantar", "Se puede cruzar si no viene nadie", "Solo la pueden cruzar los autobuses", "Indica el borde de la calzada"],
    correctIndex: 0,
    explanation: "La línea continua prohíbe cruzarla, incluso para adelantamientos, salvo excepciones muy concretas (obstáculos, etc.).",
  },
  {
    category: "senales",
    text: "Una señal circular de fondo blanco con el número 30 y borde rojo indica:",
    options: ["Velocidad máxima de 30 km/h", "Velocidad mínima de 30 km/h", "Que quedan 30 km hasta el destino", "Que hay 30 plazas de aparcamiento"],
    correctIndex: 0,
    explanation: "Es una señal de prohibición (velocidad máxima autorizada), de ahí su borde rojo.",
  },
  {
    category: "senales",
    text: "Una señal circular de fondo azul con el mismo número (30) pero sin borde rojo indicaría en cambio:",
    options: ["Velocidad mínima obligatoria de 30 km/h", "Velocidad máxima de 30 km/h", "Fin de la limitación de velocidad", "Zona de aparcamiento limitado a 30 minutos"],
    correctIndex: 0,
    explanation: "Las señales circulares de fondo azul sin borde rojo son de obligación; en este caso, velocidad mínima.",
  },
  {
    category: "senales",
    text: "Una señal cuadrada azul con un peatón caminando y una bicicleta indica normalmente:",
    options: ["Vía o acera compartida para peatones y ciclistas", "Prohibido el paso a peatones y ciclistas", "Zona exclusiva para peatones", "Paso de ciclistas con prioridad absoluta sobre vehículos"],
    correctIndex: 0,
    explanation: "Es una señal de indicación que delimita un itinerario compartido para peatones y bicicletas.",
  },
  {
    category: "senales",
    text: "La señal de 'Zona de Bajas Emisiones' (ZBE) implica que:",
    options: ["Puede haber restricciones de acceso según la etiqueta ambiental del vehículo", "Está prohibido circular con cualquier vehículo", "Solo pueden entrar bicicletas", "Es obligatorio apagar el motor al entrar"],
    correctIndex: 0,
    explanation: "En las ZBE, cada vez más ciudades restringen el acceso a vehículos sin etiqueta ambiental o con las etiquetas más contaminantes.",
  },
  {
    category: "senales",
    text: "Un panel rectangular adicional bajo una señal de peligro que indica una distancia (p. ej. '300 m') significa:",
    options: ["La distancia hasta el punto donde empieza el peligro señalizado", "La distancia recorrida desde el último pueblo", "El límite de velocidad a partir de ahí", "La longitud del atasco"],
    correctIndex: 0,
    explanation: "Los paneles complementarios aportan información adicional, como la distancia a la que se encuentra el peligro anunciado.",
  },
  {
    category: "senales",
    text: "Una flecha amarilla intermitente en un panel de mensaje variable sobre un carril suele indicar:",
    options: ["Que ese carril va a cerrarse próximamente, se debe cambiar de carril", "Que ese carril tiene prioridad absoluta", "Que se puede circular en cualquier sentido", "Que el carril es solo para autobuses"],
    correctIndex: 0,
    explanation: "Los paneles de mensaje variable avisan con antelación de cierres de carril para que el conductor pueda cambiar de carril con seguridad.",
  },

  // ---- PRIORIDAD ----
  {
    category: "prioridad",
    text: "En una intersección sin señales de prioridad, ¿quién tiene preferencia?",
    options: ["El vehículo que llega por la derecha", "El vehículo más grande", "El que circula más rápido", "El primero que toque el claxon"],
    correctIndex: 0,
    explanation: "A falta de señalización, rige la regla de prioridad de paso por la derecha.",
  },
  {
    category: "prioridad",
    text: "En una rotonda, la prioridad general es para:",
    options: ["Los vehículos que ya circulan dentro de la rotonda", "Los vehículos que van a entrar", "El vehículo más grande", "El que entra por la izquierda"],
    correctIndex: 0,
    explanation: "Quien circula dentro de la rotonda tiene prioridad sobre quien pretende incorporarse.",
  },
  {
    category: "prioridad",
    text: "¿Cuándo se debe ceder el paso a un vehículo de emergencia con señales luminosas y acústicas activadas?",
    options: ["Siempre, facilitándole el paso lo antes posible y de forma segura", "Solo si viene por detrás", "Solo en autovías", "Nunca, ellos deben adaptarse al tráfico"],
    correctIndex: 0,
    explanation: "Los vehículos prioritarios en servicio de urgencia tienen preferencia de paso; el resto debe facilitarles la circulación.",
  },
  {
    category: "prioridad",
    text: "Al incorporarse a una vía desde un carril de aceleración, el conductor debe:",
    options: ["Ceder el paso a los vehículos que ya circulan por la vía principal", "Tener siempre prioridad", "Detenerse obligatoriamente antes de incorporarse", "Adelantar antes de incorporarse"],
    correctIndex: 0,
    explanation: "Quien se incorpora desde un carril de aceleración debe ceder el paso a quienes ya circulan por la vía.",
  },
  {
    category: "prioridad",
    text: "En un cruce con un peatón cruzando por un paso señalizado sin semáforo, el conductor debe:",
    options: ["Detenerse y dejarle cruzar", "Tocar el claxon para que se dé prisa", "Pasar si el peatón aún no ha bajado del todo a la calzada", "Adelantarlo por detrás"],
    correctIndex: 0,
    explanation: "Los peatones tienen prioridad en los pasos de peatones señalizados; el conductor debe detenerse.",
  },
  {
    category: "prioridad",
    text: "Dos vehículos llegan a la vez a una intersección sin señalizar, uno de frente y otro girando a la izquierda desde el sentido contrario. ¿Quién tiene prioridad?",
    options: ["El vehículo que circula de frente", "El que gira a la izquierda", "Ninguno, deben parar ambos indefinidamente", "El vehículo más nuevo"],
    correctIndex: 0,
    explanation: "El vehículo que gira debe ceder el paso al que circula de frente en sentido contrario.",
  },
  {
    category: "prioridad",
    text: "¿Qué indica una señal de 'Intersección con prioridad'?",
    options: ["Que la vía por la que se circula tiene prioridad sobre las que se crucen", "Que hay que ceder el paso en el próximo cruce", "Que se aproxima una rotonda", "Que la vía se va a estrechar"],
    correctIndex: 0,
    explanation: "Esta señal informa de que se mantiene la prioridad de paso en los cruces sucesivos hasta que se indique lo contrario.",
  },
  {
    category: "prioridad",
    text: "En un tramo de carretera estrecho donde solo cabe un vehículo, si se cruzan un turismo y un camión, ¿quién debe ceder normalmente el paso?",
    options: ["El vehículo que tenga más facilidad para maniobrar o retroceder con seguridad", "Siempre el turismo", "Siempre el camión", "El que vaya más rápido"],
    correctIndex: 0,
    explanation: "Ante un obstáculo o paso estrecho, cede quien pueda hacerlo con mayor facilidad y seguridad, aunque hay reglas específicas según el desnivel o el tipo de vía.",
  },
  {
    category: "prioridad",
    text: "Circulando por una vía y queriendo girar a la derecha, cruzándose con un ciclista que sigue recto por el carril bici, el conductor debe:",
    options: ["Ceder el paso al ciclista antes de girar", "Girar primero porque va en la misma dirección", "Adelantar al ciclista justo antes del giro", "Tocar el claxon para que frene"],
    correctIndex: 0,
    explanation: "El vehículo que gira debe ceder el paso a los ciclistas que continúan de frente por su carril.",
  },
  {
    category: "prioridad",
    text: "¿Qué se debe hacer al aproximarse a un paso a nivel sin barreras con la señal de STOP?",
    options: ["Detenerse, mirar y escuchar antes de cruzar", "Cruzar rápido para no quedarse atrapado", "Solo reducir la velocidad", "Tocar el claxon y cruzar"],
    correctIndex: 0,
    explanation: "En pasos a nivel sin barreras señalizados con STOP es obligatorio detenerse y verificar que no se aproxima ningún tren.",
  },
  {
    category: "prioridad",
    text: "Un autobús de transporte público que sale de una parada señalizada, con el intermitente puesto, en vía urbana:",
    options: ["Tiene prioridad para incorporarse y el resto debe facilitarle el paso si es seguro", "Nunca tiene prioridad sobre otros vehículos", "Solo tiene prioridad en autopista", "Debe esperar siempre a que pase todo el tráfico"],
    correctIndex: 0,
    explanation: "Los autobuses que se ponen en marcha desde una parada señalizada tienen preferencia para incorporarse al tráfico cuando indican su maniobra.",
  },
  {
    category: "prioridad",
    text: "En una rotonda de varios carriles, para salir por la primera salida a la derecha, en general conviene:",
    options: ["Circular por el carril derecho de la rotonda desde la entrada", "Circular siempre por el carril central", "Da igual el carril, se puede cambiar en el último segundo", "Circular por el carril izquierdo"],
    correctIndex: 0,
    explanation: "Para salidas próximas conviene entrar y circular por el carril derecho, señalizando la salida con antelación.",
  },

  // ---- VELOCIDAD ----
  {
    category: "velocidad",
    text: "En una vía urbana con un único carril por sentido de circulación, sin otra señalización, la velocidad genérica máxima es:",
    options: ["30 km/h", "50 km/h", "20 km/h", "70 km/h"],
    correctIndex: 0,
    explanation: "Desde la reforma de 2021, el genérico en calles de un solo carril por sentido es 30 km/h; en calles con plataforma única para vehículos y peatones es 20 km/h; y en vías de dos o más carriles por sentido, 50 km/h.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "En una vía urbana de dos o más carriles por sentido de circulación, sin otra señalización, la velocidad genérica máxima es:",
    options: ["50 km/h", "30 km/h", "70 km/h", "90 km/h"],
    correctIndex: 0,
    explanation: "El límite genérico sube a 50 km/h cuando la vía urbana tiene dos o más carriles por sentido; con un solo carril por sentido baja a 30 km/h.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "En una calle con plataforma única, sin distinción de acera y calzada (todo al mismo nivel), la velocidad genérica máxima es:",
    options: ["20 km/h", "30 km/h", "50 km/h", "10 km/h"],
    correctIndex: 0,
    explanation: "Las calles de plataforma única (habituales en cascos históricos) tienen un límite genérico de 20 km/h por la convivencia directa con peatones.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "La distancia de seguridad con el vehículo de delante debe permitir:",
    options: ["Detenerse a tiempo si este frena bruscamente", "Adelantarlo en cualquier momento", "Ver la matrícula del vehículo de delante", "Tocar el claxon si se acerca demasiado"],
    correctIndex: 0,
    explanation: "La distancia de seguridad debe ser suficiente para poder parar sin colisionar si el vehículo precedente frena.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "Circular a una velocidad excesiva para las condiciones de la vía (lluvia, niebla, curvas) aunque no se supere el límite señalizado es:",
    options: ["Una infracción, porque la velocidad debe adaptarse a las circunstancias", "Correcto siempre que no se supere el límite", "Solo sancionable de noche", "Solo aplicable a camiones"],
    correctIndex: 0,
    explanation: "El límite señalizado es un máximo; siempre debe adaptarse la velocidad a las condiciones reales (visibilidad, tráfico, firme, etc.).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "El exceso de velocidad reduce sobre todo:",
    options: ["El tiempo de reacción disponible y aumenta la distancia de frenado", "Únicamente el consumo de combustible", "El desgaste de los neumáticos, sin más efectos", "Solamente la comodidad del viaje"],
    correctIndex: 0,
    explanation: "A mayor velocidad, mayor distancia recorrida durante el tiempo de reacción y mayor distancia de frenado (crece de forma cuadrática).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "En autopista o autovía, un turismo sin remolque circula, con carácter general, a una velocidad máxima de:",
    options: ["120 km/h", "100 km/h", "90 km/h", "140 km/h"],
    correctIndex: 0,
    explanation: "El límite genérico para turismos en autopista/autovía es 120 km/h, salvo señalización distinta.",
  },
  {
    category: "velocidad",
    text: "¿Qué es la 'huella de frenada'?",
    options: ["La marca dejada por los neumáticos al frenar bruscamente", "La distancia de seguridad recomendada", "El desgaste normal del neumático", "Una señal en el asfalto"],
    correctIndex: 0,
    explanation: "Es la marca visible en el pavimento que deja un neumático al bloquearse durante un frenazo intenso.",
  },
  {
    category: "velocidad",
    text: "Al circular en un túnel, respecto a la distancia con el vehículo de delante hay que:",
    options: ["Aumentar la precaución y mantener mayor distancia de seguridad", "Reducirla porque hay menos espacio", "Es indiferente", "Solo aplica si el túnel es muy largo"],
    correctIndex: 0,
    explanation: "En túneles se recomienda aumentar la distancia de seguridad por la menor visibilidad y mayor riesgo en caso de incidente.",
  },
  {
    category: "velocidad",
    text: "La 'regla de los dos segundos' se usa para:",
    options: ["Calcular una distancia de seguridad orientativa con el vehículo de delante", "Medir el tiempo de un adelantamiento", "Saber cuánto dura el ámbar de un semáforo", "Calcular el tiempo de frenada en mojado"],
    correctIndex: 0,
    explanation: "Consiste en dejar pasar al menos dos segundos entre que el vehículo de delante pasa por un punto y tú pasas por el mismo punto.",
  },
  {
    category: "velocidad",
    text: "En condiciones de lluvia, la distancia de seguridad respecto a la habitual debe:",
    options: ["Aumentarse, al menos duplicándola", "Mantenerse igual", "Reducirse porque se circula más despacio", "Da igual si se llevan neumáticos nuevos"],
    correctIndex: 0,
    explanation: "Con el firme mojado la adherencia disminuye y la distancia de frenado aumenta, por lo que conviene aumentar considerablemente la distancia de seguridad.",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "Para un ciclomotor o motocicleta sin autorización especial, en general los límites de velocidad:",
    options: ["Se ajustan a las características técnicas del vehículo y a los límites de la vía", "Son siempre superiores a los de los turismos", "No existen en ninguna vía", "Solo aplican en ciudad"],
    correctIndex: 0,
    explanation: "Cada tipo de vehículo tiene límites específicos según sus características, además de respetar el límite general de la vía.",
  },
  {
    category: "velocidad",
    text: "En una carretera convencional (un carril por sentido), sin otra señalización, la velocidad genérica máxima para un turismo es:",
    options: ["90 km/h", "100 km/h", "110 km/h", "80 km/h"],
    correctIndex: 0,
    explanation: "El límite genérico en carretera convencional es 90 km/h; puede llegar a 100 km/h si la vía tiene arcén pavimentado de un mínimo de 1,5 metros.",
  },
  {
    category: "velocidad",
    text: "La 'regla del cuadrado' que propone la DGT para calcular la distancia de seguridad orientativa consiste en:",
    options: [
      "Coger la velocidad, quitarle el último dígito y multiplicar el resultado por sí mismo",
      "Multiplicar la velocidad por dos",
      "Dividir la velocidad entre el número de carriles",
      "Sumar 10 metros por cada 10 km/h de velocidad",
    ],
    correctIndex: 0,
    explanation: "Por ejemplo, a 90 km/h: 9 × 9 = 81 metros de distancia de seguridad recomendada en calzada seca.",
  },
  {
    category: "velocidad",
    text: "Según la 'regla del cuadrado', circulando a 120 km/h en calzada mojada, la distancia de seguridad recomendada es aproximadamente:",
    options: ["288 metros (el doble que en seco)", "144 metros, igual que en seco", "72 metros, la mitad que en seco", "12 metros"],
    correctIndex: 0,
    explanation: "En calzada mojada se recomienda duplicar la distancia calculada para calzada seca (12² = 144, ×2 = 288 metros).",
    isSerious: true,
  },
  {
    category: "velocidad",
    text: "Circular muy por debajo de la velocidad normal de los demás vehículos sin causa justificada, entorpeciendo la circulación:",
    options: ["También puede ser una infracción", "Nunca es sancionable, cuanto más despacio mejor", "Solo es sancionable en autopista", "Es obligatorio si hay niños en el coche"],
    correctIndex: 0,
    explanation: "La velocidad debe adaptarse a la vía; circular anormalmente despacio sin motivo también puede constituir infracción por entorpecer la circulación.",
  },

  // ---- ALCOHOL Y DROGAS ----
  {
    category: "alcohol-drogas",
    text: "El alcohol en el organismo afecta principalmente a:",
    options: ["El tiempo de reacción y la percepción del riesgo", "Solo a la vista nocturna", "Solo al sentido del oído", "Nada si se ha comido bien antes"],
    correctIndex: 0,
    explanation: "El alcohol ralentiza los reflejos, reduce la percepción del peligro y produce exceso de confianza.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Conducir bajo los efectos de bebidas alcohólicas por encima de las tasas legales es:",
    options: ["Una infracción grave o muy grave según la tasa, con posibles consecuencias penales", "Solo una recomendación a evitar", "Legal si se conduce despacio", "Solo sancionable de noche"],
    correctIndex: 0,
    explanation: "Superar las tasas de alcoholemia permitidas constituye infracción administrativa (y puede ser delito según la tasa) con sanciones económicas y de puntos.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "La fatiga y el sueño al volante:",
    options: ["Aumentan mucho el riesgo de accidente y deben evitarse descansando", "No afectan si se lleva la radio encendida", "Se solucionan abriendo la ventanilla", "Solo afectan en viajes de más de 1000 km"],
    correctIndex: 0,
    explanation: "El cansancio reduce la atención y los reflejos; la única solución eficaz es parar y descansar.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "El consumo de determinados medicamentos (ansiolíticos, antihistamínicos, etc.) antes de conducir:",
    options: ["Puede afectar a la capacidad de conducción y debe consultarse el prospecto", "Nunca afecta a la conducción", "Solo afecta si se toman de noche", "Mejora los reflejos"],
    correctIndex: 0,
    explanation: "Muchos medicamentos producen somnolencia o afectan a los reflejos; hay que revisar el prospecto y el pictograma correspondiente.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Tras consumir drogas, aunque sea en pequeña cantidad, para conducir:",
    options: ["Está prohibido conducir, hay tolerancia cero", "Se puede conducir si han pasado 2 horas", "Solo está prohibido de noche", "Depende del tipo de vehículo"],
    correctIndex: 0,
    explanation: "Para las drogas la legislación aplica tolerancia cero: cualquier resultado positivo es infracción.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "¿Qué efecto produce el alcohol sobre el campo visual?",
    options: ["Lo reduce, produciendo una especie de 'visión en túnel'", "Lo amplía notablemente", "No tiene ningún efecto", "Mejora la visión nocturna"],
    correctIndex: 0,
    explanation: "El alcohol reduce el campo visual periférico, dificultando detectar peligros laterales.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Un conductor novel (con menos de determinada experiencia) tiene, respecto al alcohol, tasas de alcoholemia permitidas:",
    options: ["Más restrictivas que un conductor experimentado", "Iguales que cualquier otro conductor", "Más permisivas", "No aplican tasas específicas"],
    correctIndex: 0,
    explanation: "Conductores noveles y profesionales suelen tener límites de alcoholemia más bajos que el resto.",
  },
  {
    category: "alcohol-drogas",
    text: "La negativa a someterse a las pruebas de detección de alcohol o drogas que ordene un agente es:",
    options: ["Un delito", "Una simple recomendación que se puede rechazar sin consecuencias", "Solo aplicable a profesionales", "Legal si el conductor no ha bebido"],
    correctIndex: 0,
    explanation: "Negarse a las pruebas de alcoholemia o drogas constituye delito, independientemente del resultado que se hubiera obtenido.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Beber café o ducharse tras haber consumido alcohol:",
    options: ["No elimina el alcohol del organismo más rápido, solo el tiempo lo hace", "Elimina el alcohol al instante", "Reduce la tasa de alcoholemia inmediatamente", "Hace que el etilómetro no detecte alcohol"],
    correctIndex: 0,
    explanation: "Solo el paso del tiempo elimina el alcohol de la sangre; no existen remedios caseros eficaces.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "El alcohol favorece especialmente la sensación de:",
    options: ["Exceso de confianza y subestimación del riesgo", "Mayor prudencia al volante", "Mejora de los reflejos", "Mayor concentración"],
    correctIndex: 0,
    explanation: "Uno de los efectos más peligrosos del alcohol es que genera una falsa sensación de seguridad y minimiza la percepción del riesgo.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "La tasa máxima de alcohol permitida con carácter general para un conductor experimentado es:",
    options: ["0,25 mg/l en aire espirado (0,5 g/l en sangre)", "0,15 mg/l en aire espirado", "0,50 mg/l en aire espirado", "No existe límite si no se ha bebido en exceso"],
    correctIndex: 0,
    explanation: "El límite general vigente es 0,25 mg/l en aire espirado, equivalente a 0,5 g/l en sangre.",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Para conductores noveles (menos de 2 años de carnet) y conductores profesionales, la tasa máxima de alcohol permitida es:",
    options: ["0,15 mg/l en aire espirado (0,3 g/l en sangre)", "0,25 mg/l en aire espirado, igual que el resto", "0,50 mg/l en aire espirado", "1,0 g/l en sangre"],
    correctIndex: 0,
    explanation: "Noveles y profesionales tienen un límite más restrictivo: 0,15 mg/l en aire espirado (0,3 g/l en sangre).",
    isSerious: true,
  },
  {
    category: "alcohol-drogas",
    text: "Superar la tasa de 0,50 mg/l en aire espirado (0,30 para noveles/profesionales) conlleva, entre otras consecuencias:",
    options: ["Una multa de 1.000 € y la retirada de 6 puntos del carné", "Solo una advertencia verbal", "La pérdida de 2 puntos como máximo", "Ninguna sanción si es la primera vez"],
    correctIndex: 0,
    explanation: "A partir de esa tasa, la sanción administrativa habitual es de 1.000 € y 6 puntos, sin perjuicio de que tasas más altas puedan constituir delito penal.",
    isSerious: true,
  },

  // ---- MECANICA Y DOCUMENTACION ----
  {
    category: "mecanica-documentos",
    text: "La profundidad mínima legal del dibujo de los neumáticos en un turismo es de:",
    options: ["1,6 mm", "3 mm", "0,5 mm", "5 mm"],
    correctIndex: 0,
    explanation: "El mínimo legal en la Unión Europea para turismos es 1,6 mm de profundidad en el dibujo principal.",
  },
  {
    category: "mecanica-documentos",
    text: "¿Qué documento acredita que un vehículo ha superado los controles técnicos periódicos?",
    options: ["El certificado/pegatina de la ITV en vigor", "El permiso de circulación", "La ficha técnica original", "El seguro obligatorio"],
    correctIndex: 0,
    explanation: "La ITV (Inspección Técnica de Vehículos) certifica que el vehículo cumple las condiciones técnicas de seguridad y medioambientales.",
  },
  {
    category: "mecanica-documentos",
    text: "Circular sin el seguro obligatorio en vigor es:",
    options: ["Una infracción muy grave", "Una infracción leve", "Legal si el vehículo es muy nuevo", "Solo se sanciona si hay accidente"],
    correctIndex: 0,
    explanation: "Circular sin seguro obligatorio se considera infracción muy grave, con independencia de que se produzca o no un siniestro.",
  },
  {
    category: "mecanica-documentos",
    text: "Si durante la marcha se enciende el testigo rojo de presión de aceite, se debe:",
    options: ["Detener el vehículo lo antes posible con seguridad y revisar el nivel", "Seguir circulando con normalidad", "Aumentar la velocidad para llegar antes al taller", "Apagar y encender el motor para que se apague el testigo"],
    correctIndex: 0,
    explanation: "El testigo rojo de aceite indica un fallo grave de lubricación; continuar circulando puede dañar seriamente el motor.",
  },
  {
    category: "mecanica-documentos",
    text: "La presión de los neumáticos inferior a la recomendada por el fabricante provoca:",
    options: ["Mayor desgaste, peor adherencia y mayor consumo", "Mejor adherencia en curva", "Menor consumo de combustible", "Ningún efecto relevante"],
    correctIndex: 0,
    explanation: "Una presión insuficiente aumenta la superficie de contacto de forma irregular, deteriora el neumático y empeora el comportamiento del vehículo.",
  },
  {
    category: "mecanica-documentos",
    text: "El líquido de frenos debe revisarse porque:",
    options: ["Con el tiempo absorbe humedad y pierde eficacia", "Nunca necesita revisión", "Se debe cambiar solo si cambia de color", "Solo afecta a vehículos diésel"],
    correctIndex: 0,
    explanation: "El líquido de frenos es higroscópico (absorbe agua), lo que reduce su punto de ebullición y la eficacia de frenada; se recomienda cambiarlo periódicamente.",
  },
  {
    category: "mecanica-documentos",
    text: "¿Qué es el permiso de circulación?",
    options: ["El documento administrativo que autoriza a un vehículo a circular", "El carné de conducir del titular", "El justificante del seguro", "El resultado de la ITV"],
    correctIndex: 0,
    explanation: "El permiso de circulación es el documento que matricula y autoriza la circulación de un vehículo concreto.",
  },
  {
    category: "mecanica-documentos",
    text: "Un chaleco reflectante y los triángulos de preseñalización deben usarse:",
    options: ["Al detenerse en el arcén por avería o accidente, para señalizar y ser visible", "Solo de noche", "Solo en autopistas de peaje", "Únicamente si lo pide un agente"],
    correctIndex: 0,
    explanation: "Es obligatorio colocarse el chaleco antes de bajar del vehículo detenido en el arcén y señalizar con los triángulos (o la V16 si aplica) para avisar a otros conductores.",
  },
  {
    category: "mecanica-documentos",
    text: "Un turismo nuevo, ¿cuándo pasa su primera ITV?",
    options: ["A los 4 años de su matriculación", "A los 6 meses", "Nunca, si tiene menos de 8 años", "Al año de matriculación"],
    correctIndex: 0,
    explanation: "Los turismos están exentos de ITV los 4 primeros años desde su matriculación.",
  },
  {
    category: "mecanica-documentos",
    text: "Un turismo de 6 años de antigüedad debe pasar la ITV:",
    options: ["Cada 2 años", "Cada 6 meses", "Cada año", "Nunca más, ya pasó la primera"],
    correctIndex: 0,
    explanation: "Entre los 4 y los 10 años de antigüedad, la periodicidad de la ITV para turismos es cada 2 años.",
  },
  {
    category: "mecanica-documentos",
    text: "Un turismo de más de 10 años de antigüedad debe pasar la ITV:",
    options: ["Cada año", "Cada 2 años, igual que uno más nuevo", "Cada 5 años", "Solo si falla algo visiblemente"],
    correctIndex: 0,
    explanation: "Superados los 10 años de antigüedad, la periodicidad de la ITV para turismos pasa a ser anual.",
  },
  {
    category: "mecanica-documentos",
    text: "Si el consumo de combustible aumenta de forma anómala sin motivo aparente, puede deberse a:",
    options: ["Un mal ajuste del motor, neumáticos deshinchados o filtros sucios, entre otras causas", "Nunca a un problema mecánico", "Siempre a la calidad del combustible", "Al color del vehículo"],
    correctIndex: 0,
    explanation: "Un aumento anómalo del consumo suele indicar un problema mecánico (motor, neumáticos, filtros) que conviene revisar.",
  },
  {
    category: "mecanica-documentos",
    text: "El desgaste irregular de un neumático (más gastado en el centro que en los laterales) suele indicar:",
    options: ["Exceso de presión", "Falta de presión", "Un neumático nuevo", "Que el vehículo es diésel"],
    correctIndex: 0,
    explanation: "Una presión excesiva concentra el desgaste en el centro de la banda de rodadura; la falta de presión lo concentra en los laterales.",
  },

  // ---- SEGURIDAD VIAL Y PRIMEROS AUXILIOS ----
  {
    category: "seguridad-vial",
    text: "Ante un accidente de tráfico, la primera actuación del primer interviniente debe ser:",
    options: ["Proteger la zona para evitar más accidentes (señalizar, balizar)", "Mover a los heridos inmediatamente", "Llamar primero a la familia de los heridos", "Retirar los vehículos de la calzada de inmediato en todos los casos"],
    correctIndex: 0,
    explanation: "La secuencia PAS (Proteger, Avisar, Socorrer) empieza siempre por proteger el lugar del accidente.",
  },
  {
    category: "seguridad-vial",
    text: "Al llamar al 112 tras un accidente, es importante indicar:",
    options: ["Ubicación exacta, número de heridos y su estado aparente", "Solo la matrícula de los vehículos", "El nombre del seguro", "Nada, ellos ya lo saben todo"],
    correctIndex: 0,
    explanation: "Dar una ubicación precisa y describir el número y estado de los heridos ayuda a movilizar los recursos adecuados.",
  },
  {
    category: "seguridad-vial",
    text: "¿Se debe quitar el casco a un motorista herido tras un accidente?",
    options: ["Solo si es imprescindible para reanimarlo y por personal con la técnica adecuada", "Sí, siempre y lo antes posible", "Nunca bajo ninguna circunstancia", "Solo si el motorista lo pide"],
    correctIndex: 0,
    explanation: "Retirar el casco de forma incorrecta puede agravar lesiones cervicales; solo se retira si es necesario para reanimación y con la técnica adecuada.",
  },
  {
    category: "seguridad-vial",
    text: "El cinturón de seguridad debe usarse:",
    options: ["Siempre, tanto en plazas delanteras como traseras cuando exista", "Solo en autopista", "Solo por el conductor", "Solo en trayectos largos"],
    correctIndex: 0,
    explanation: "El cinturón es obligatorio para todos los ocupantes en todas las plazas equipadas con él, en cualquier vía.",
  },
  {
    category: "seguridad-vial",
    text: "Los sistemas de retención infantil (sillitas) deben usarse:",
    options: ["Según la talla/peso del menor, según lo indicado por la normativa vigente", "Solo si el niño lo pide", "Solo en viajes largos", "Nunca en el asiento delantero bajo ninguna circunstancia"],
    correctIndex: 0,
    explanation: "La normativa exige el uso de sistemas de retención adaptados a la talla y peso del menor hasta cierta estatura/edad.",
  },
  {
    category: "seguridad-vial",
    text: "Ante un vehículo averiado en el arcén, antes de bajarse del coche los ocupantes deben:",
    options: ["Ponerse el chaleco reflectante", "Encender las luces largas", "Bajar todos a la vez por el lado de la calzada", "Abrir todas las puertas"],
    correctIndex: 0,
    explanation: "Es obligatorio colocarse el chaleco reflectante antes de salir del vehículo detenido en el arcén o calzada.",
  },
  {
    category: "seguridad-vial",
    text: "El uso del teléfono móvil sujeto con la mano mientras se conduce es:",
    options: ["Una infracción grave, aunque sea en un semáforo en rojo", "Legal si el vehículo está parado en un semáforo", "Legal siempre que sea una llamada corta", "Solo se sanciona de noche"],
    correctIndex: 0,
    explanation: "Usar el móvil sujeto con la mano mientras se conduce está prohibido y es infracción grave, incluso detenido en un semáforo si el motor no está apagado.",
  },
  {
    category: "seguridad-vial",
    text: "En caso de vuelco o incendio de un vehículo con ocupantes atrapados y en peligro inminente, ¿se puede mover a un herido?",
    options: ["Sí, solo si existe un peligro inminente y no hay otra alternativa", "Nunca, bajo ninguna circunstancia", "Sí, siempre que sea posible aunque no haya peligro", "Solo si lo autoriza un médico por teléfono"],
    correctIndex: 0,
    explanation: "La norma general es no mover a un herido, salvo peligro inminente (incendio, riesgo de nuevo atropello, etc.) en que no quede otra opción.",
  },
  {
    category: "seguridad-vial",
    text: "El punto ciego de un vehículo es:",
    options: ["La zona alrededor del vehículo que no se ve por los retrovisores ni directamente", "Una avería del sistema de luces", "La parte del parabrisas sucia", "El área delante del capó"],
    correctIndex: 0,
    explanation: "Son zonas, especialmente a los laterales traseros, donde otros vehículos pueden quedar ocultos a la vista del conductor.",
  },
  {
    category: "seguridad-vial",
    text: "Desde el 1 de enero de 2026, para señalizar un turismo inmovilizado en la calzada o el arcén, la normativa establece que:",
    options: [
      "La baliza V16 conectada es el medio de señalización exigido, sustituyendo a los triángulos",
      "Solo se pueden usar los triángulos de preseñalización",
      "No es obligatorio señalizar el vehículo si son las horas centrales del día",
      "Basta con encender las luces de posición",
    ],
    correctIndex: 0,
    explanation: "La baliza V16 conectada es obligatoria desde el 1 de enero de 2026 para turismos, vehículos mixtos, camiones y autobuses (no para motocicletas). No se sanciona usar también los triángulos junto a ella.",
  },
  {
    category: "seguridad-vial",
    text: "No llevar la baliza V16 homologada y conectada cuando la normativa lo exige supone:",
    options: ["Una multa (en torno a 80 €, sin pérdida de puntos)", "La retirada inmediata del carné", "6 puntos menos en el carné", "La inmovilización del vehículo siempre"],
    correctIndex: 0,
    explanation: "Es una infracción sancionada económicamente, sin detracción de puntos.",
  },
  {
    category: "seguridad-vial",
    text: "El protocolo básico de actuación ante un accidente se resume en las siglas PAS, que significan:",
    options: ["Proteger, Avisar, Socorrer", "Parar, Analizar, Salir", "Proteger, Analizar, Socorrer", "Parar, Avisar, Seguir"],
    correctIndex: 0,
    explanation: "PAS es la secuencia recomendada: primero proteger la zona, después avisar a emergencias, y por último socorrer a los heridos si se sabe cómo hacerlo con seguridad.",
  },
  {
    category: "seguridad-vial",
    text: "Ante una persona inconsciente que respira, tras comprobar que no hay peligro inminente, se recomienda colocarla en:",
    options: ["Posición lateral de seguridad", "Boca abajo con los brazos extendidos", "Sentada con la cabeza hacia atrás", "De pie apoyada en el vehículo"],
    correctIndex: 0,
    explanation: "La posición lateral de seguridad evita que la persona se ahogue con su propia lengua o vómito mientras espera ayuda.",
  },
  {
    category: "seguridad-vial",
    text: "La fatiga visual y la falta de descanso en viajes largos se combaten sobre todo:",
    options: ["Parando a descansar cada cierto tiempo (aprox. cada 2 horas)", "Subiendo el volumen de la música", "Bajando la ventanilla únicamente", "Aumentando la velocidad para llegar antes"],
    correctIndex: 0,
    explanation: "Se recomienda parar a descansar aproximadamente cada 2 horas o 200 km en viajes largos para evitar la fatiga acumulada.",
  },

  // ---- ADELANTAMIENTO ----
  {
    category: "adelantamiento",
    text: "Como norma general, ¿está permitido adelantar en una curva o cambio de rasante de visibilidad reducida?",
    options: ["No, está prohibido si no se ve todo el tramo necesario para completar la maniobra", "Sí, siempre que se avise con el intermitente", "Sí, si no viene nadie de frente", "Solo de día"],
    correctIndex: 0,
    explanation: "El adelantamiento exige ver con claridad todo el espacio necesario para completarlo con seguridad; en curvas o cambios de rasante sin visibilidad suficiente está prohibido.",
  },
  {
    category: "adelantamiento",
    text: "¿Se puede adelantar en un paso de peatones señalizado o en sus proximidades?",
    options: ["No, está prohibido", "Sí, si no hay peatones cruzando en ese momento", "Sí, tocando el claxon antes", "Solo si el peatón cede el paso"],
    correctIndex: 0,
    explanation: "Está prohibido adelantar en pasos de peatones señalizados y en sus proximidades, haya o no peatones cruzando en ese instante.",
  },
  {
    category: "adelantamiento",
    text: "Dentro de un túnel con un único carril por sentido, adelantar está:",
    options: ["Prohibido, como norma general", "Siempre permitido", "Permitido solo a motocicletas", "Permitido si el túnel mide menos de 200 metros"],
    correctIndex: 0,
    explanation: "El adelantamiento está prohibido dentro de túneles con un solo carril por sentido; sí se permite si el túnel tiene dos o más carriles para el mismo sentido.",
  },
  {
    category: "adelantamiento",
    text: "¿Está permitido adelantar dentro de una glorieta?",
    options: ["Sí, si las dimensiones y la circulación lo permiten con seguridad", "No, nunca está permitido en glorietas", "Solo a los autobuses", "Solo si la glorieta tiene semáforos"],
    correctIndex: 0,
    explanation: "Las glorietas son una excepción: se puede adelantar dentro de ellas si el espacio y las condiciones lo permiten sin riesgo.",
  },
  {
    category: "adelantamiento",
    text: "Al ser adelantado por otro vehículo, el conductor adelantado debe:",
    options: ["Facilitar la maniobra sin acelerar ni entorpecer", "Acelerar para que el adelantamiento sea más rápido", "Cambiar de carril inmediatamente", "Encender las luces largas"],
    correctIndex: 0,
    explanation: "Quien es adelantado no debe aumentar su velocidad ni dificultar la maniobra del vehículo que adelanta.",
  },
  {
    category: "adelantamiento",
    text: "¿Se puede adelantar a un ciclista en un tramo señalizado como 'prohibido adelantar'?",
    options: ["Sí, respetando la distancia lateral de seguridad exigida", "No, la prohibición aplica a cualquier vehículo o usuario", "Solo de noche", "Solo si el ciclista lo autoriza con un gesto"],
    correctIndex: 0,
    explanation: "Las prohibiciones de adelantamiento admiten excepciones para rebasar bicicletas, ciclomotores, peatones o animales, siempre con la distancia de separación adecuada y sin riesgo.",
  },
  {
    category: "adelantamiento",
    text: "Antes de iniciar un adelantamiento en carretera convencional, el conductor debe comprobar, entre otras cosas:",
    options: [
      "Que dispone de espacio y visibilidad suficientes y que nadie le esté ya adelantando a él",
      "Solo que el vehículo de delante circula despacio",
      "Que hay línea discontinua en algún punto del tramo",
      "Que el vehículo de delante no lleva las luces de emergencia encendidas",
    ],
    correctIndex: 0,
    explanation: "Antes de adelantar hay que verificar visibilidad, espacio suficiente y que ningún vehículo esté iniciando ya el adelantamiento del propio vehículo.",
  },
  {
    category: "adelantamiento",
    text: "¿Está permitido adelantar en una intersección o cruce?",
    options: ["No, como norma general, ni tampoco en sus proximidades", "Sí, siempre que haya semáforo en verde", "Sí, si el cruce tiene rotonda", "Solo fuera de poblado"],
    correctIndex: 0,
    explanation: "Las intersecciones y sus proximidades son, junto con pasos a nivel, pasos de peatones, curvas y túneles, lugares donde el adelantamiento está prohibido con carácter general.",
  },
  {
    category: "adelantamiento",
    text: "Al adelantar a un vehículo largo (como un camión) en carretera, la distancia de seguridad lateral y el tiempo de maniobra deben ser:",
    options: ["Mayores que al adelantar un turismo", "Los mismos que para cualquier vehículo", "Menores, porque el camión va más despacio", "Irrelevantes si hay línea discontinua"],
    correctIndex: 0,
    explanation: "Los vehículos largos requieren más tiempo y espacio para completar el adelantamiento con seguridad.",
  },
  {
    category: "adelantamiento",
    text: "¿Es correcto adelantar por el arcén en una autovía o autopista?",
    options: ["No, el arcén no es un carril de circulación", "Sí, si hay atasco en los carriles normales", "Sí, solo con moto", "Sí, si se pone el intermitente"],
    correctIndex: 0,
    explanation: "El arcén está reservado para paradas de emergencia y vehículos prioritarios; no debe usarse para adelantar ni para circular con normalidad.",
  },
  {
    category: "adelantamiento",
    text: "Un vehículo que circula mucho más lento que el resto del tráfico, en carretera, debe:",
    options: ["Facilitar que le adelanten, aproximándose al borde derecho cuando sea posible", "Circular por el centro del carril para no dejar adelantar", "Adelantar a los demás aunque vaya más lento", "Acelerar cuando note que alguien quiere adelantarlo"],
    correctIndex: 0,
    explanation: "Los vehículos lentos deben facilitar los adelantamientos aproximándose al borde derecho de la calzada cuando sea seguro.",
  },
  {
    category: "adelantamiento",
    text: "En una vía de doble sentido con línea discontinua en tu carril y continua en el contrario, tú:",
    options: ["Puedes adelantar si el resto de condiciones de seguridad lo permiten", "No puedes adelantar bajo ninguna circunstancia", "Solo puede adelantar el vehículo del carril contrario", "Debes esperar a que ambas líneas sean discontinuas"],
    correctIndex: 0,
    explanation: "La línea discontinua en tu lado permite cruzarla para adelantar; la continua en el lado contrario indica que esos conductores no deben invadir tu carril para adelantar.",
  },

  // ---- PARADA Y ESTACIONAMIENTO ----
  {
    category: "parada-estacionamiento",
    text: "¿Cuál es la diferencia entre 'parada' y 'estacionamiento'?",
    options: [
      "La parada es una inmovilización breve sin abandonar el vehículo o para operaciones rápidas; el estacionamiento es más prolongado",
      "No hay ninguna diferencia legal",
      "La parada solo se permite en autopista",
      "El estacionamiento solo se aplica a motocicletas",
    ],
    correctIndex: 0,
    explanation: "La parada es una inmovilización de corta duración (p. ej. para subir o bajar pasajeros); el estacionamiento implica dejar el vehículo inmovilizado sin necesidad de permanecer junto a él.",
  },
  {
    category: "parada-estacionamiento",
    text: "¿Está permitido parar o estacionar en un paso de peatones?",
    options: ["No, está prohibido", "Sí, unos minutos", "Sí, si se encienden las luces de emergencia", "Solo de noche"],
    correctIndex: 0,
    explanation: "Pasos de peatones, pasos de ciclistas y sus proximidades son lugares donde la parada y el estacionamiento están prohibidos.",
  },
  {
    category: "parada-estacionamiento",
    text: "¿Se puede estacionar en un carril reservado para bicicletas o transporte público?",
    options: ["No, está prohibido", "Sí, fuera del horario de servicio del transporte público", "Sí, si el vehículo es pequeño", "Sí, siempre que sea de noche"],
    correctIndex: 0,
    explanation: "Los carriles reservados no pueden usarse para estacionar, ya que son para la circulación de esos vehículos específicos.",
  },
  {
    category: "parada-estacionamiento",
    text: "Una línea amarilla continua junto al bordillo indica:",
    options: ["Prohibido parar y estacionar", "Prohibido solo estacionar, se puede parar", "Zona de carga y descarga libre", "Zona de aparcamiento gratuito"],
    correctIndex: 0,
    explanation: "La línea amarilla continua señala una prohibición total de parada y estacionamiento en ese tramo.",
  },
  {
    category: "parada-estacionamiento",
    text: "Una línea amarilla discontinua junto al bordillo indica:",
    options: ["Prohibido estacionar, pero se permite la parada breve", "Prohibido parar y estacionar", "Aparcamiento reservado para residentes", "Zona de velocidad reducida"],
    correctIndex: 0,
    explanation: "La línea amarilla discontinua prohíbe el estacionamiento, pero permite paradas de corta duración.",
  },
  {
    category: "parada-estacionamiento",
    text: "¿Está permitido estacionar en doble fila?",
    options: ["No, como norma general está prohibido", "Sí, siempre que se pongan las luces de emergencia", "Sí, menos de 5 minutos", "Sí, en calles de un solo sentido"],
    correctIndex: 0,
    explanation: "Estacionar en doble fila está prohibido, ya que obstaculiza gravemente la circulación, aunque se pongan las luces de emergencia.",
  },
  {
    category: "parada-estacionamiento",
    text: "Al estacionar en una vía con pendiente, además de frenar, se recomienda:",
    options: ["Dejar una marcha metida (o 'P' en automático) y girar las ruedas hacia el bordillo o cuneta", "Dejar el vehículo en punto muerto sin más", "Quitar el freno de mano para no forzarlo", "Estacionar siempre en sentido contrario a la marcha"],
    correctIndex: 0,
    explanation: "En pendiente conviene dejar una marcha puesta y orientar las ruedas para que, si el vehículo se moviera, no invada la calzada.",
  },
  {
    category: "parada-estacionamiento",
    text: "¿Se puede parar o estacionar en el arcén de una autopista salvo emergencia?",
    options: ["No, el arcén se reserva para casos de necesidad justificada (avería, emergencia)", "Sí, para hacer una foto rápida", "Sí, para descansar unos minutos sin más", "Sí, siempre que el vehículo tenga baliza V16"],
    correctIndex: 0,
    explanation: "Detenerse en el arcén de autopista/autovía solo se permite por causa justificada, como una avería o una emergencia real.",
  },
  {
    category: "parada-estacionamiento",
    text: "Estacionar frente a un vado señalizado y en uso:",
    options: ["Está prohibido, aunque no se vea utilizar el vado en ese momento", "Está permitido si es solo un momento", "Solo está prohibido de noche", "Depende de si el vado tiene la placa numerada visible"],
    correctIndex: 0,
    explanation: "Los vados señalizados prohíben el estacionamiento frente a ellos en todo momento, no solo cuando se observa que se está usando.",
  },
  {
    category: "parada-estacionamiento",
    text: "En zona de estacionamiento limitado (zona azul/verde), superar el tiempo pagado:",
    options: ["Puede dar lugar a sanción por estacionamiento indebido", "Nunca tiene consecuencias", "Solo afecta si se supera en más de un día", "Es gratis los primeros 30 minutos siempre"],
    correctIndex: 0,
    explanation: "Excederse del tiempo abonado en zonas de estacionamiento regulado puede ser sancionado como estacionamiento indebido.",
  },
  {
    category: "parada-estacionamiento",
    text: "¿Se puede estacionar sobre la acera?",
    options: ["No, está prohibido con carácter general", "Sí, si el coche es pequeño", "Sí, si se deja sitio para pasar un cochecito de bebé", "Sí, en calles muy estrechas"],
    correctIndex: 0,
    explanation: "Estacionar sobre la acera está prohibido porque invade el espacio reservado a los peatones.",
  },
  {
    category: "parada-estacionamiento",
    text: "Al abandonar el vehículo tras estacionar en vía pública, es recomendable:",
    options: ["Comprobar que no queda ningún elemento sobresaliendo que estorbe a otros usuarios", "Dejar las luces de posición encendidas siempre", "Dejar una ventanilla abierta siempre", "Dejar el motor encendido"],
    correctIndex: 0,
    explanation: "Se debe evitar que puertas, maleteros o elementos del vehículo obstaculicen la circulación de otros vehículos o peatones.",
  },

  // ---- LUCES Y ALUMBRADO ----
  {
    category: "luces",
    text: "Dentro de un túnel, aunque sea de día y esté iluminado, es obligatorio llevar encendido:",
    options: ["El alumbrado de cruce (luces cortas)", "Solo las luces de posición", "Las luces largas", "No es obligatorio ningún alumbrado si el túnel está iluminado"],
    correctIndex: 0,
    explanation: "En túneles y tramos señalizados con la señal de Túnel es obligatorio circular con las luces de cruce encendidas a cualquier hora del día.",
  },
  {
    category: "luces",
    text: "Con niebla densa, aunque sea de día, se debe circular con:",
    options: ["Las luces de cruce encendidas (y antiniebla si la visibilidad es muy reducida)", "Solo las luces de posición", "Las luces largas para ver más lejos", "Sin ninguna luz para no deslumbrar"],
    correctIndex: 0,
    explanation: "Cuando la niebla, lluvia intensa u otras condiciones reducen sensiblemente la visibilidad, es obligatorio encender el alumbrado de cruce, y las antiniebla si la visibilidad es muy escasa.",
  },
  {
    category: "luces",
    text: "Al cruzarse con otro vehículo de noche en carretera, con las luces largas puestas, se debe:",
    options: ["Cambiar a luces de cruce para no deslumbrar al otro conductor", "Mantener las largas si se va más rápido", "Apagar todas las luces un instante", "Encender también las antiniebla"],
    correctIndex: 0,
    explanation: "Las luces largas deslumbran a quien viene de frente; deben cambiarse a cruce antes de cruzarse con otro vehículo.",
  },
  {
    category: "luces",
    text: "Las luces de posición (de noche, en una vía sin iluminación, con el vehículo detenido) deben:",
    options: ["Permanecer encendidas para que el vehículo sea visible", "Apagarse siempre al detenerse", "Sustituirse por las luces de emergencia obligatoriamente", "Ser opcionales si hay luna llena"],
    correctIndex: 0,
    explanation: "Un vehículo detenido de noche en vía sin iluminación suficiente debe permanecer visible, normalmente con las luces de posición encendidas.",
  },
  {
    category: "luces",
    text: "Las luces antiniebla traseras se deben usar:",
    options: ["Solo cuando la visibilidad esté realmente muy reducida (niebla intensa, nevada, lluvia fuerte)", "Siempre que llueva un poco", "Cada vez que anochece", "Nunca, están prohibidas"],
    correctIndex: 0,
    explanation: "Usarlas sin necesidad puede deslumbrar y confundir a quien circula detrás; se reservan para condiciones de visibilidad muy reducida.",
  },
  {
    category: "luces",
    text: "¿Cuándo es obligatorio el uso de las luces de emergencia (los 'cuatro intermitentes')?",
    options: ["Cuando el vehículo circula o está detenido en situación de peligro para el resto de usuarios", "Siempre que llueva", "Al aparcar en zona azul", "Al circular por autopista de noche"],
    correctIndex: 0,
    explanation: "Se usan para advertir de una situación de peligro puntual, como una avería, un frenazo brusco inesperado o un atasco repentino.",
  },
  {
    category: "luces",
    text: "Circular de noche por vía interurbana sin ningún tipo de alumbrado encendido es:",
    options: ["Una infracción grave", "Correcto si hay luna llena", "Correcto si se circula despacio", "Solo sancionable si hay accidente"],
    correctIndex: 0,
    explanation: "Circular sin alumbrado obligatorio de noche es una infracción grave por el riesgo que supone para la propia seguridad y la de terceros.",
  },
  {
    category: "luces",
    text: "Al circular de día por una vía interurbana normal (sin túnel, niebla ni lluvia), las motocicletas deben llevar:",
    options: ["El alumbrado de cruce encendido siempre, de día y de noche", "Ninguna luz encendida de día", "Solo las luces de posición", "Solo si el conductor lo decide"],
    correctIndex: 0,
    explanation: "Las motocicletas y ciclomotores deben circular siempre con la luz de cruce encendida, también de día, para ser más visibles.",
  },
  {
    category: "luces",
    text: "¿Qué luz debe usarse al efectuar una maniobra de marcha atrás?",
    options: ["La luz de marcha atrás, que se enciende automáticamente al meter esa marcha", "Las luces largas", "Las luces antiniebla traseras", "Ninguna, no es necesaria"],
    correctIndex: 0,
    explanation: "La luz de marcha atrás avisa a quienes están detrás de que el vehículo va a retroceder.",
  },
  {
    category: "luces",
    text: "Circular con una sola luz de cruce fundida (por ejemplo, de noche) es:",
    options: ["Una deficiencia que debe repararse cuanto antes, puede ser sancionable", "Totalmente indiferente para la seguridad", "Solo un problema estético", "Legal si la otra luz es muy potente"],
    correctIndex: 0,
    explanation: "Una luz fundida reduce la visibilidad del vehículo y puede confundir a otros conductores sobre su anchura real; debe repararse cuanto antes.",
  },

  // ---- SANCIONES Y PUNTOS ----
  {
    category: "sanciones-puntos",
    text: "Las infracciones de tráfico se clasifican, según su gravedad, en:",
    options: ["Leves, graves y muy graves", "Solo leves y graves", "Administrativas y penales únicamente", "Locales y estatales"],
    correctIndex: 0,
    explanation: "El texto articulado de la Ley de Tráfico clasifica las infracciones en leves, graves y muy graves, con distinta sanción económica y de puntos.",
  },
  {
    category: "sanciones-puntos",
    text: "Las infracciones leves, como norma general:",
    options: ["No conllevan pérdida de puntos del carné", "Siempre restan al menos 2 puntos", "Restan más puntos que las graves", "Suponen la retirada del carné"],
    correctIndex: 0,
    explanation: "Las infracciones leves se sancionan solo económicamente (hasta 100 €, o 50 € con pronto pago), sin pérdida de puntos.",
  },
  {
    category: "sanciones-puntos",
    text: "Usar el teléfono móvil sujeto con la mano mientras se conduce supone:",
    options: ["200 € de multa y 6 puntos menos", "Solo una amonestación verbal", "100 € de multa sin puntos", "2 puntos menos únicamente"],
    correctIndex: 0,
    explanation: "Es una de las infracciones más penalizadas: 200 € y 6 puntos, igual se esté circulando o parado con el motor en marcha (p. ej. en un semáforo).",
  },
  {
    category: "sanciones-puntos",
    text: "Manipular el teléfono móvil colocado en un soporte homologado mientras se conduce, o llevar auriculares en ambos oídos:",
    options: ["También es sancionable: 200 € y 3 puntos menos", "Es totalmente legal sin restricciones", "Solo es sancionable de noche", "Resta 6 puntos, igual que sujetarlo con la mano"],
    correctIndex: 0,
    explanation: "Aunque el móvil esté en un soporte, manipularlo mientras se conduce está sancionado (200 € y 3 puntos), igual que llevar auriculares en ambos oídos.",
  },
  {
    category: "sanciones-puntos",
    text: "Un conductor que obtiene el permiso por primera vez (novel) comienza con:",
    options: ["8 puntos, que pasan a 12 si no comete infracciones que resten puntos en 2 años", "15 puntos desde el primer día", "12 puntos desde el primer día", "20 puntos, como cualquier conductor"],
    correctIndex: 0,
    explanation: "Los conductores noveles empiezan con 8 puntos; si pasan 2 años sin infracciones que resten puntos, suben a 12, el saldo habitual del resto de conductores.",
  },
  {
    category: "sanciones-puntos",
    text: "El saldo máximo de puntos que puede alcanzar un conductor con antigüedad y sin sanciones es:",
    options: ["15 puntos", "8 puntos", "20 puntos", "10 puntos"],
    correctIndex: 0,
    explanation: "Con años de conducción sin perder puntos, el saldo puede llegar hasta un máximo de 15 puntos.",
  },
  {
    category: "sanciones-puntos",
    text: "Si un conductor llega a 0 puntos en su carné:",
    options: ["Pierde la vigencia del permiso y debe recuperarlo mediante curso y, en su caso, nuevo examen", "No pasa nada, sigue pudiendo conducir con normalidad", "Solo se le avisa por carta", "Pierde 6 meses de validez del carné, pero conserva los puntos restantes"],
    correctIndex: 0,
    explanation: "Al llegar a 0 puntos se pierde la vigencia del permiso; para recuperarlo hace falta un curso de recuperación de puntos y, según el caso, superar de nuevo las pruebas.",
  },
  {
    category: "sanciones-puntos",
    text: "¿Cuántos puntos como máximo se pueden perder en un mismo día, aunque se cometan varias infracciones distintas?",
    options: ["8 puntos", "Sin límite, se suman todos", "2 puntos", "15 puntos"],
    correctIndex: 0,
    explanation: "La normativa limita a 8 puntos la pérdida máxima en un mismo día, con independencia del número de infracciones cometidas ese día.",
  },
  {
    category: "sanciones-puntos",
    text: "Los cursos de recuperación parcial de puntos permiten recuperar:",
    options: ["Hasta 4 puntos, si aún queda saldo en el carné", "Todos los puntos perdidos, sin límite", "1 punto como máximo", "Solo se puede hacer un curso en toda la vida"],
    correctIndex: 0,
    explanation: "Estos cursos voluntarios permiten recuperar hasta 4 puntos, siempre que el conductor todavía conserve saldo de puntos (no haya llegado a 0).",
  },
  {
    category: "sanciones-puntos",
    text: "Conducir tras haber sido privado judicial o administrativamente del permiso de conducir es:",
    options: ["Un delito", "Una infracción leve", "Una infracción grave sin más consecuencias", "Legal si es una urgencia"],
    correctIndex: 0,
    explanation: "Conducir sin permiso por haber perdido su vigencia (p. ej. por pérdida total de puntos) o estando privado de él judicialmente puede constituir delito.",
  },
  {
    category: "sanciones-puntos",
    text: "Instalar y usar un inhibidor de radares en el vehículo:",
    options: ["Es una infracción muy grave, con importante pérdida de puntos", "Es legal si se usa solo en autopista", "Es legal si el inhibidor está apagado la mayor parte del tiempo", "Solo está prohibido para camiones"],
    correctIndex: 0,
    explanation: "El uso de inhibidores o detectores de radar está prohibido y se sanciona como infracción muy grave.",
  },
  {
    category: "sanciones-puntos",
    text: "Circular en sentido contrario al establecido en una vía:",
    options: ["Es una infracción muy grave, con importante pérdida de puntos", "Es leve si se hace marcha atrás", "Solo es infracción de noche", "No tiene sanción de puntos, solo económica"],
    correctIndex: 0,
    explanation: "Circular en sentido contrario es una de las conductas más peligrosas y se sanciona como infracción muy grave.",
  },

  // ---- MENORES Y TRANSPORTE DE PERSONAS ----
  {
    category: "menores-transporte",
    text: "¿A partir de qué estatura puede un menor viajar sin sistema de retención infantil (SRI), usando solo el cinturón del vehículo?",
    options: ["A partir de 135 cm", "A partir de 100 cm", "A partir de 12 años, sin importar la estatura", "Nunca, hasta la mayoría de edad"],
    correctIndex: 0,
    explanation: "El criterio principal es la estatura: los menores de 135 cm deben usar un SRI adecuado a su talla y peso.",
  },
  {
    category: "menores-transporte",
    text: "Un menor de estatura inferior a 135 cm, ¿puede viajar en el asiento delantero?",
    options: ["Solo en casos excepcionales (p. ej. si no caben todos los SRI atrás) y con el sistema de retención adecuado", "Sí, siempre sin ninguna restricción", "No, nunca bajo ninguna circunstancia", "Sí, sin necesidad de silla si va en brazos de un adulto"],
    correctIndex: 0,
    explanation: "La norma general obliga a los menores de 135 cm a viajar detrás; el asiento delantero solo se admite en supuestos excepcionales tasados (p. ej. plazas traseras insuficientes) y siempre con SRI.",
  },
  {
    category: "menores-transporte",
    text: "Si se instala una silla infantil a contramarcha en el asiento delantero, es obligatorio:",
    options: ["Desactivar el airbag frontal de ese asiento", "Dejar el airbag activado siempre", "Retirar el reposacabezas", "Bajar la ventanilla durante el trayecto"],
    correctIndex: 0,
    explanation: "El despliegue del airbag frontal con una silla a contramarcha puede causar lesiones graves al bebé; por eso debe desactivarse en ese caso.",
  },
  {
    category: "menores-transporte",
    text: "Se recomienda que los bebés viajen en sillas orientadas a contramarcha (mirando hacia atrás) al menos hasta:",
    options: ["Los 15 meses de edad", "Los 3 meses de edad", "El primer día de vida solamente", "Los 8 años de edad"],
    correctIndex: 0,
    explanation: "Viajar a contramarcha protege mejor el cuello y la columna del bebé en caso de colisión frontal; se recomienda mantenerlo así al menos hasta los 15 meses.",
  },
  {
    category: "menores-transporte",
    text: "El cinturón de seguridad en plazas traseras equipadas con él es obligatorio para:",
    options: ["Todos los ocupantes, en cualquier tipo de vía", "Solo en autopista", "Solo para los adultos, no para los menores con SRI", "Solo si el trayecto dura más de 30 minutos"],
    correctIndex: 0,
    explanation: "El cinturón es obligatorio en todas las plazas que dispongan de él, también en las traseras, en cualquier vía.",
  },
  {
    category: "menores-transporte",
    text: "Un autocar de transporte escolar detenido con las señales reglamentarias activadas para recoger o dejar niños:",
    options: ["Obliga a los demás vehículos a extremar la precaución y, según la señalización, detenerse", "No implica ninguna obligación especial para el resto de vehículos", "Solo afecta a otros autobuses", "Únicamente aplica en autopista"],
    correctIndex: 0,
    explanation: "Los vehículos de transporte escolar tienen una señalización específica que obliga al resto de conductores a reducir la velocidad y extremar las precauciones por la presencia de menores.",
  },
  {
    category: "menores-transporte",
    text: "En un vehículo sin plazas traseras (p. ej. un dos plazas), un menor de estatura inferior a 135 cm:",
    options: ["Puede viajar delante con el SRI adecuado a su talla, como excepción justificada", "No puede viajar en ese vehículo bajo ninguna circunstancia", "Puede viajar sin ningún sistema de retención", "Debe viajar siempre tumbado en el maletero"],
    correctIndex: 0,
    explanation: "La ausencia de plazas traseras es una de las excepciones reconocidas que permite instalar el SRI en el asiento delantero.",
  },
  {
    category: "menores-transporte",
    text: "El número máximo de ocupantes de un turismo viene determinado por:",
    options: ["El número de plazas homologadas indicado en su ficha técnica", "El tamaño del maletero", "El criterio del conductor, sin límite legal", "El número de cinturones delanteros únicamente"],
    correctIndex: 0,
    explanation: "No se puede superar el número de plazas autorizadas en la ficha técnica del vehículo, cada una con su cinturón correspondiente.",
  },
  {
    category: "menores-transporte",
    text: "Llevar a un menor sin el sistema de retención infantil obligatorio es:",
    options: ["Una infracción grave para el conductor", "Una infracción leve sin importancia", "Solo una recomendación, no una obligación legal", "Responsabilidad exclusiva de los padres, nunca del conductor"],
    correctIndex: 0,
    explanation: "El incumplimiento de la normativa de SRI es responsabilidad del conductor del vehículo y se sanciona como infracción grave.",
  },
  {
    category: "menores-transporte",
    text: "Entre los 135 y 150 cm de estatura, aunque ya se permita el cinturón normal, ¿qué recomienda la DGT?",
    options: ["Seguir usando un SRI (elevador) homologado a esa talla mientras sea posible", "Prescindir de cualquier sistema de retención", "Usar solo el cinturón abdominal, sin el diagonal", "Viajar siempre en el maletero"],
    correctIndex: 0,
    explanation: "Aunque legalmente ya se permite el cinturón a partir de 135 cm, el ajuste del cinturón mejora con un elevador homologado hasta aproximadamente los 150 cm.",
  },

  // ---- MEDIO AMBIENTE Y CONDUCCIÓN EFICIENTE ----
  {
    category: "medio-ambiente",
    text: "La etiqueta ambiental CERO de la DGT (distintivo azul) se reserva a:",
    options: ["Vehículos eléctricos, de hidrógeno o híbridos enchufables de mayor autonomía eléctrica", "Todos los vehículos diésel modernos", "Cualquier vehículo de gasolina posterior a 2015", "Los vehículos con más de 8 plazas"],
    correctIndex: 0,
    explanation: "La etiqueta CERO se reserva a los vehículos de cero o casi cero emisiones: eléctricos puros, de hidrógeno e híbridos enchufables con autonomía eléctrica suficiente.",
  },
  {
    category: "medio-ambiente",
    text: "La etiqueta ambiental ECO se asigna, entre otros, a:",
    options: ["Híbridos no enchufables y vehículos de gas que cumplen determinada normativa de emisiones", "Solo a vehículos eléctricos", "Solo a vehículos diésel anteriores a 2010", "A cualquier turismo de más de 10 años"],
    correctIndex: 0,
    explanation: "La etiqueta ECO cubre híbridos no enchufables, híbridos enchufables de menor autonomía y vehículos propulsados por gas, cumpliendo cierta normativa de emisiones.",
  },
  {
    category: "medio-ambiente",
    text: "En una Zona de Bajas Emisiones (ZBE) de una gran ciudad, un vehículo sin etiqueta ambiental:",
    options: ["Puede tener restringido el acceso o ser sancionado", "Puede circular sin ninguna restricción", "Solo tiene restricciones los fines de semana", "Solo afecta a camiones, nunca a turismos"],
    correctIndex: 0,
    explanation: "Las ZBE de ciudades de cierto tamaño restringen o sancionan el acceso a los vehículos sin distintivo ambiental o con los más contaminantes.",
  },
  {
    category: "medio-ambiente",
    text: "La conducción eficiente (eco-driving) recomienda, entre otras cosas:",
    options: ["Anticiparse al tráfico y mantener una velocidad estable, evitando acelerones y frenazos", "Acelerar y frenar bruscamente para llegar antes", "Circular siempre con marchas cortas a alta revolución", "Llevar los neumáticos con menos presión de la recomendada"],
    correctIndex: 0,
    explanation: "Anticiparse y suavizar la conducción reduce el consumo de combustible, las emisiones y el desgaste del vehículo.",
  },
  {
    category: "medio-ambiente",
    text: "Circular con el aire acondicionado o los accesorios eléctricos innecesarios encendidos:",
    options: ["Aumenta el consumo de combustible y las emisiones", "No tiene ningún efecto en el consumo", "Reduce el consumo de combustible", "Solo afecta a vehículos eléctricos"],
    correctIndex: 0,
    explanation: "Cualquier consumo eléctrico o mecánico adicional incrementa la carga del motor y, por tanto, el consumo y las emisiones.",
  },
  {
    category: "medio-ambiente",
    text: "Una presión de neumáticos inferior a la recomendada por el fabricante, además de ser peligrosa, provoca:",
    options: ["Mayor consumo de combustible", "Menor consumo de combustible", "Ningún efecto sobre el consumo", "Solo afecta a la estética del neumático"],
    correctIndex: 0,
    explanation: "Una presión insuficiente aumenta la resistencia a la rodadura, lo que se traduce en mayor consumo de combustible.",
  },
  {
    category: "medio-ambiente",
    text: "Cambiar de marcha a bajas revoluciones (sin apurar el motor) en un cambio manual:",
    options: ["Reduce el consumo de combustible y las emisiones", "Aumenta siempre el consumo", "Estropea la caja de cambios", "Es obligatorio hacerlo solo en autopista"],
    correctIndex: 0,
    explanation: "Cambiar de marcha pronto, sin apurar las revoluciones, es una de las bases de la conducción eficiente.",
  },
  {
    category: "medio-ambiente",
    text: "El etiquetado ambiental de un vehículo depende principalmente de:",
    options: ["Su tipo de motorización y el nivel de emisiones que cumple (normativa Euro, etc.)", "El color de la carrocería", "El número de puertas del vehículo", "El precio de compra del vehículo"],
    correctIndex: 0,
    explanation: "La etiqueta se asigna según el tipo de motor (eléctrico, híbrido, gasolina, diésel, gas) y la normativa de emisiones que cumple.",
  },
  {
    category: "medio-ambiente",
    text: "Reducir la velocidad y mantener una distancia de seguridad adecuada, además de ser más seguro:",
    options: ["Contribuye a reducir el consumo de combustible", "No tiene relación con el consumo de combustible", "Siempre aumenta el consumo", "Solo influye en el desgaste de los frenos"],
    correctIndex: 0,
    explanation: "Una conducción más suave y con menos frenazos bruscos, derivada de mantener distancia y velocidad adecuadas, reduce el consumo.",
  },

  // ---- AUTOPISTAS, AUTOVÍAS Y VÍAS ESPECIALES ----
  {
    category: "autopistas-vias-especiales",
    text: "¿Cuál es la principal diferencia entre autopista y autovía?",
    options: [
      "La autopista es de peaje o gestión especial y no tiene cruces a nivel ni accesos directos a fincas; la autovía puede tener algunos accesos y cruces regulados",
      "La autovía siempre es de peaje y la autopista siempre gratuita",
      "No existe ninguna diferencia legal entre ambas",
      "La autopista es solo para camiones",
    ],
    correctIndex: 0,
    explanation: "Ambas tienen calzadas separadas y varios carriles por sentido, pero la autopista tiene un régimen jurídico especial (a menudo de peaje) y accesos más restringidos que la autovía.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "En autopista o autovía, ¿pueden circular los peatones, ciclomotores o bicicletas?",
    options: ["No, tienen prohibido el acceso salvo excepciones muy concretas", "Sí, sin ninguna restricción", "Solo los ciclomotores, no los peatones", "Solo de noche"],
    correctIndex: 0,
    explanation: "Autopistas y autovías están reservadas a determinados vehículos motorizados; peatones, bicicletas y ciclomotores tienen prohibido su acceso, salvo excepciones tasadas.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "El carril de aceleración al incorporarse a una autovía sirve para:",
    options: ["Alcanzar una velocidad similar a la del tráfico antes de incorporarse", "Adelantar a los vehículos que ya circulan por la autovía", "Aparcar temporalmente", "Circular en sentido contrario si hay atasco"],
    correctIndex: 0,
    explanation: "El carril de aceleración permite ganar velocidad para incorporarse con seguridad, cediendo el paso a quienes ya circulan por la vía principal.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "Si se pasa la salida deseada en una autopista o autovía, el conductor debe:",
    options: ["Continuar hasta la siguiente salida, nunca dar marcha atrás ni parar", "Detenerse y dar marcha atrás por el arcén", "Cruzar la mediana si es posible", "Girar en redondo en la propia calzada"],
    correctIndex: 0,
    explanation: "Está terminantemente prohibido circular marcha atrás, detenerse o cambiar de sentido en autopistas y autovías; hay que ir hasta la siguiente salida.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "El carril izquierdo en una autopista o autovía de varios carriles se reserva, con carácter general, para:",
    options: ["Adelantamientos, no para circular de forma habitual", "Vehículos lentos", "Aparcamiento de emergencia", "Vehículos de transporte escolar"],
    correctIndex: 0,
    explanation: "El carril izquierdo debe usarse para adelantar y volver después al carril derecho, no para circular de manera continuada.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "En una vía para automóviles (distinta de autopista/autovía, señalizada específicamente), ¿pueden circular los ciclomotores?",
    options: ["No, están reservadas a automóviles", "Sí, sin restricción", "Solo los ciclomotores de más de 50 cc", "Solo si van acompañados de un coche"],
    correctIndex: 0,
    explanation: "Las 'vías para automóviles' están reservadas a la circulación de automóviles, excluyendo ciclomotores, bicicletas y peatones.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "Detenerse en el carril de deceleración de una salida de autovía cuando aún no se ha decidido salir:",
    options: ["No es correcto, ese carril es exclusivamente para decelerar y salir", "Es correcto si hay mucho tráfico", "Es obligatorio si vas a salir en la siguiente", "Solo está permitido a camiones"],
    correctIndex: 0,
    explanation: "El carril de deceleración debe usarse solo por quienes van a tomar esa salida, no como zona de espera o parada.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "En una autovía con niebla y visibilidad muy reducida, se recomienda además de encender las luces:",
    options: ["Reducir notablemente la velocidad y aumentar la distancia de seguridad", "Mantener la misma velocidad de siempre", "Circular pegado al vehículo de delante para verlo mejor", "Usar las luces largas para ver más lejos"],
    correctIndex: 0,
    explanation: "En condiciones de niebla se debe reducir la velocidad y aumentar mucho la distancia de seguridad, además del alumbrado adecuado.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "Si un vehículo sufre una avería en plena autopista y no puede salir de la calzada, los ocupantes deben:",
    options: ["Ponerse el chaleco reflectante antes de salir y situarse en zona segura, fuera de la calzada si es posible", "Permanecer todos dentro del vehículo con el motor en marcha", "Bajarse y quedarse junto a la puerta del conductor", "Empujar el vehículo hasta la siguiente salida"],
    correctIndex: 0,
    explanation: "La prioridad es la seguridad de los ocupantes: chaleco reflectante, señalización del vehículo y alejarse de la calzada si es posible, a zona segura.",
  },

  // ---- SEÑALES (segunda tanda) ----
  {
    category: "senales",
    text: "Una señal octogonal roja con la palabra 'STOP' es única en su forma para que:",
    options: ["Se distinga incluso desde atrás o si está sucia, por su silueta", "Se pueda confundir con un ceda el paso", "Sea más barata de fabricar", "Solo la reconozcan los conductores noveles"],
    correctIndex: 0,
    explanation: "La forma octogonal es exclusiva del STOP precisamente para poder reconocerla por su silueta en cualquier circunstancia.",
  },
  {
    category: "senales",
    text: "Una marca vial en forma de rombo blanco en el suelo, antes de un paso de peatones, avisa de:",
    options: ["La proximidad de un paso de peatones", "Un paso de ciclistas", "El final de una prohibición", "Un cambio de sentido"],
    correctIndex: 0,
    explanation: "El rombo pintado en el pavimento anuncia con antelación que se aproxima un paso de peatones.",
  },
  {
    category: "senales",
    text: "Una señal con silueta de un ciervo indica:",
    options: ["Peligro por paso de animales en libertad", "Zona de caza permitida", "Un zoológico cercano", "Prohibido el paso de animales"],
    correctIndex: 0,
    explanation: "Es una señal de peligro (triangular) que advierte de la posible presencia de animales cruzando la vía.",
  },
  {
    category: "senales",
    text: "Una señal rectangular azul con una 'P' indica:",
    options: ["Zona de estacionamiento", "Prohibido aparcar", "Parada de autobús exclusivamente", "Precaución, curva peligrosa"],
    correctIndex: 0,
    explanation: "Es una señal de indicación de servicio: informa de la existencia de una zona habilitada para estacionar.",
  },
  {
    category: "senales",
    text: "Una señal triangular con dos líneas convergentes en forma de embudo indica:",
    options: ["Estrechamiento de calzada", "Cruce de doble sentido", "Fin de autopista", "Zona de obras permanente"],
    correctIndex: 0,
    explanation: "Advierte de que la calzada se estrecha más adelante y puede ser necesario reducir la velocidad o ceder el paso.",
  },
  {
    category: "senales",
    text: "Cuando un semáforo tiene una flecha verde adicional junto al círculo en rojo, permite:",
    options: ["Girar en el sentido de la flecha con precaución, cediendo el paso, aunque el círculo esté en rojo", "Ignorar cualquier flecha si el círculo está en rojo", "Avanzar recto igualmente", "Aparcar en ese carril"],
    correctIndex: 0,
    explanation: "La flecha verde permite girar en esa dirección concreta cediendo el paso a peatones y otros vehículos, incluso con el semáforo circular en rojo.",
  },
  {
    category: "senales",
    text: "Una señal de peligro con el dibujo de una carretera resbaladiza (coche patinando) indica:",
    options: ["Riesgo de pérdida de adherencia del pavimento", "Zona de lavado de coches", "Obligación de poner cadenas", "Fin de la zona de peligro"],
    correctIndex: 0,
    explanation: "Advierte de un firme deslizante (hielo, aceite, humedad) que puede reducir la adherencia de los neumáticos.",
  },

  // ---- LUCES (segunda tanda) ----
  {
    category: "luces",
    text: "El destello de las luces (ráfagas) se puede usar para:",
    options: ["Advertir a otro conductor de la propia presencia, con moderación", "Obligar a otro vehículo a apartarse siempre", "Sustituir al intermitente", "Indicar que se va a adelantar sin más consideración"],
    correctIndex: 0,
    explanation: "Las ráfagas sirven para advertir de la presencia del vehículo, nunca para intimidar o imponerse a otros usuarios.",
  },
  {
    category: "luces",
    text: "Los ciclomotores y motocicletas, en cuanto al alumbrado obligatorio de día, están equiparados a:",
    options: ["La obligación de llevar la luz de cruce encendida en todo momento", "No tienen ninguna obligación de alumbrado de día", "Solo deben llevar luces de noche", "Solo deben llevar antiniebla"],
    correctIndex: 0,
    explanation: "Motocicletas y ciclomotores deben circular siempre, de día y de noche, con el alumbrado de cruce encendido.",
  },
  {
    category: "luces",
    text: "Un remolque o caravana enganchado a un turismo debe llevar, entre otras luces:",
    options: ["Sus propias luces de posición, freno e intermitentes traseras", "Ninguna luz propia, basta con las del turismo", "Solo luz de matrícula", "Solo luces antiniebla"],
    correctIndex: 0,
    explanation: "El remolque debe tener su propio sistema de luces traseras (posición, freno, intermitentes) para ser visible y comunicar sus maniobras.",
  },
  {
    category: "luces",
    text: "¿Cuándo deben encenderse las luces de posición delanteras y traseras según la normativa general?",
    options: ["Entre el ocaso y la orto del sol, y siempre que las condiciones de visibilidad lo exijan", "Solo cuando el conductor lo considere estético", "Nunca, solo hacen falta las de cruce", "Solo los fines de semana"],
    correctIndex: 0,
    explanation: "Las luces de posición son obligatorias desde el anochecer hasta el amanecer, además de en cualquier situación de visibilidad reducida.",
  },
  {
    category: "luces",
    text: "Circular con las luces antiniebla delanteras y traseras encendidas sin que existan condiciones que lo justifiquen:",
    options: ["No es correcto, pueden deslumbrar innecesariamente a otros conductores", "Es recomendable siempre para ir más seguro", "Es obligatorio de noche en cualquier vía", "Ahorra combustible"],
    correctIndex: 0,
    explanation: "Las antiniebla deben reservarse para cuando realmente hay niebla, lluvia intensa u otra condición que reduzca mucho la visibilidad.",
  },

  // ---- MENORES Y TRANSPORTE (segunda tanda) ----
  {
    category: "menores-transporte",
    text: "El transporte escolar y de menores en autocar exige, entre otras medidas:",
    options: ["Acompañante responsable y cumplimiento de normas específicas de seguridad", "Ninguna medida especial distinta de un autocar normal", "Que el conductor tenga menos de 5 años de experiencia", "Prescindir del cinturón de seguridad"],
    correctIndex: 0,
    explanation: "El transporte escolar tiene requisitos añadidos de seguridad, como la figura del acompañante, precisamente por transportar a menores.",
  },
  {
    category: "menores-transporte",
    text: "¿Puede un adulto viajar sosteniendo a un bebé en brazos como sistema de sujeción?",
    options: ["No, no sustituye a un sistema de retención infantil homologado", "Sí, si el adulto lleva puesto el cinturón", "Sí, únicamente en trayectos urbanos cortos", "Sí, si el bebé tiene menos de 3 meses"],
    correctIndex: 0,
    explanation: "En caso de colisión, ni la fuerza de un adulto puede retener a un bebé en brazos; siempre se necesita un SRI homologado y bien anclado.",
  },
  {
    category: "menores-transporte",
    text: "Los sistemas de retención infantil (sillas, elevadores) que se instalan en el vehículo deben:",
    options: ["Estar homologados y ser adecuados a la talla y peso del menor", "Poder servir para cualquier edad sin distinción", "Ser opcionales si el trayecto es corto", "Sustituirse por un cojín cualquiera si no se dispone de uno"],
    correctIndex: 0,
    explanation: "Un SRI no homologado o inadecuado a la talla/peso del menor no ofrece la protección necesaria en caso de accidente.",
  },
  {
    category: "menores-transporte",
    text: "En taxis o vehículos de transporte con conductor (VTC), si no se dispone de SRI adecuado para un menor:",
    options: ["Existen ciertas excepciones regladas, pero la seguridad del menor sigue siendo prioritaria", "El menor puede viajar siempre sin ningún sistema de retención", "El taxi no puede llevar nunca a un menor", "Da igual, los taxis están exentos de toda norma"],
    correctIndex: 0,
    explanation: "La normativa prevé excepciones limitadas para taxis sin SRI disponible, pero el objetivo sigue siendo proteger al menor lo máximo posible.",
  },
  {
    category: "menores-transporte",
    text: "Dejar a un menor solo dentro de un vehículo estacionado, aunque sea unos minutos:",
    options: ["Es una práctica desaconsejada y potencialmente peligrosa (golpe de calor, entre otros riesgos)", "Es totalmente seguro si las ventanillas están cerradas", "Solo es peligroso en verano", "Es recomendable si el menor tiene más de 10 años"],
    correctIndex: 0,
    explanation: "La temperatura interior de un vehículo puede subir muy rápido incluso con temperaturas exteriores moderadas, poniendo en riesgo la vida del menor.",
  },

  // ---- MEDIO AMBIENTE (segunda tanda) ----
  {
    category: "medio-ambiente",
    text: "La etiqueta B se asigna, entre otros, a:",
    options: ["Turismos de gasolina matriculados desde 2001 y diésel desde 2006, con más restricciones en las ZBE", "Solo a vehículos eléctricos", "Solo a vehículos de menos de un año", "A cualquier vehículo sin importar su antigüedad"],
    correctIndex: 0,
    explanation: "La etiqueta B corresponde a vehículos de gasolina y diésel de cierta antigüedad, con más limitaciones de acceso en zonas de bajas emisiones.",
  },
  {
    category: "medio-ambiente",
    text: "Mantener el motor al ralentí de forma prolongada e innecesaria (parado con el motor encendido):",
    options: ["Genera consumo y emisiones innecesarias", "Ahorra combustible frente a apagarlo y encenderlo", "Es obligatorio siempre que se para el vehículo", "No tiene ningún impacto ambiental"],
    correctIndex: 0,
    explanation: "Mantener el motor encendido sin necesidad consume combustible y genera emisiones sin ningún beneficio para el vehículo.",
  },
  {
    category: "medio-ambiente",
    text: "Planificar la ruta con antelación para evitar tráfico y kilómetros innecesarios es una recomendación de:",
    options: ["Conducción eficiente y respetuosa con el medio ambiente", "Seguridad pasiva únicamente", "Normativa sobre neumáticos", "Uso del cinturón de seguridad"],
    correctIndex: 0,
    explanation: "Reducir kilómetros y evitar atascos disminuye el consumo de combustible y las emisiones asociadas al trayecto.",
  },
  {
    category: "medio-ambiente",
    text: "El mantenimiento periódico del vehículo (filtros, aceite, neumáticos) influye en:",
    options: ["El consumo de combustible y el nivel de emisiones contaminantes", "Únicamente en la estética del vehículo", "Solo en la garantía comercial, sin relación ambiental", "Nada relacionado con el medio ambiente"],
    correctIndex: 0,
    explanation: "Un vehículo mal mantenido consume más y contamina más; el mantenimiento adecuado ayuda a reducir ambos factores.",
  },

  // ---- AUTOPISTAS Y VÍAS ESPECIALES (segunda tanda) ----
  {
    category: "autopistas-vias-especiales",
    text: "En autopista, circular por el arcén salvo emergencia o para vehículos prioritarios es:",
    options: ["Una infracción, el arcén no es un carril de circulación ordinaria", "Correcto si hay mucho tráfico en los carriles normales", "Correcto solo para motocicletas", "Obligatorio si el vehículo circula despacio"],
    correctIndex: 0,
    explanation: "El arcén se reserva para emergencias, averías y vehículos de servicios de urgencia; usarlo para circular con normalidad es infracción.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "En un área de servicio o de descanso de autopista, antes de reincorporarse a la vía principal, el conductor debe:",
    options: ["Utilizar el carril de aceleración y ceder el paso a quienes ya circulan", "Incorporarse directamente sin comprobar el tráfico", "Detenerse en el propio carril de la autopista antes de entrar", "Tocar el claxon para avisar de la incorporación"],
    correctIndex: 0,
    explanation: "La incorporación debe hacerse ganando velocidad en el carril de aceleración y cediendo el paso al tráfico que ya circula por la vía principal.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "Los vehículos que, por su tipo, tienen prohibida la circulación por autopistas y autovías incluyen, entre otros, a:",
    options: ["Ciclomotores, bicicletas, peatones y vehículos que no puedan alcanzar la velocidad mínima exigida", "Cualquier turismo de más de 10 años", "Los vehículos de color oscuro", "Los vehículos con más de 4 ocupantes"],
    correctIndex: 0,
    explanation: "Estas vías están reservadas a vehículos motorizados capaces de circular a la velocidad mínima exigida; ciclomotores, bicicletas y peatones tienen prohibido el acceso.",
  },
  {
    category: "autopistas-vias-especiales",
    text: "En autovía, la velocidad mínima que se debe poder alcanzar para circular por ella, con carácter general, responde a que:",
    options: ["Un vehículo demasiado lento puede suponer un riesgo para el resto del tráfico rápido", "No existe ninguna velocidad mínima en ningún caso", "La velocidad mínima solo aplica en autopistas de peaje", "Solo afecta a los camiones"],
    correctIndex: 0,
    explanation: "Las vías rápidas exigen que los vehículos puedan mantener una velocidad mínima para no crear un riesgo por la gran diferencia de velocidades con el resto del tráfico.",
  },
];
