import { PieceDef } from "./defs";

// Biblioteca de piezas reales, transcritas a partir del repertorio de Arnau
// (curso Kids). El orden de mas facil a mas dificil, con las piezas de
// Navidad colocadas para diciembre, tal como se acordo con Azucena.

export const arnauPieces: PieceDef[] = [
  {
    title: "Clementine (Oh My Darling)",
    composer: "Tradicional",
    ageGroup: "KIDS",
    difficultyTier: 1,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "3/4",
    iconEmoji: "🥜",
    content: {
      clef: "treble",
      melody: ["G4", "E4", "G4", "A4", "G4", "F4", "E4", "D4", "C4"],
      melodyRhythm: [1, 1, 1, 1, 1, 1, 1, 1, 2],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4"],
      lyricsHook: "Oh, my darling, oh, my darling, oh, my darling, Clementine",
    },
  },
  {
    title: "Chopsticks",
    composer: "Euphemia Allen",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 2,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "3/4",
    iconEmoji: "🥢",
    content: {
      clef: "grand",
      melody: ["F5", "F5", "F5", "E5", "E5", "E5", "D5", "D5", "D5", "C5"],
      melodyRhythm: [1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
      bass: ["F3", "F3", "F3", "E3", "E3", "E3", "D3", "D3", "D3", "C3"],
      bassRhythm: [1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
      featuredNotes: ["C5", "D5", "E5", "F5"],
    },
  },
  {
    title: "Do Your Ears Hang Low?",
    composer: "Tradicional",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 3,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🐶",
    content: {
      clef: "grand",
      melody: ["G4", "C5", "C5", "C5", "A4", "G4", "F4", "A4", "G4", "F4", "E4", "D4", "C4"],
      melodyRhythm: [1, 1, 0.5, 0.5, 1, 1, 1, 1, 0.5, 0.5, 1, 1, 2],
      bass: ["C3", "F3", "G3", "C3"],
      bassRhythm: [1, 1, 1, 1],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4", "C5"],
      lyricsHook: "Do your ears hang low, do they wobble to and fro?",
    },
  },
  {
    title: "Baa Baa Black Sheep",
    composer: "Tradicional",
    arranger: "Jim Paterson",
    ageGroup: "KIDS",
    difficultyTier: 4,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🐑",
    content: {
      clef: "grand",
      melody: ["C4", "C4", "G4", "G4", "A4", "A4", "G4"],
      melodyRhythm: [1, 1, 1, 1, 1, 1, 2],
      bass: ["C3", "F3", "C3", "G3"],
      bassRhythm: [2, 2, 2, 2],
      chordsUsed: ["C", "F", "G"],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4"],
      lyricsHook: "Baa, baa, black sheep, have you any wool?",
    },
  },
  {
    title: "The Wheels on the Bus",
    composer: "Tradicional",
    arranger: "Jim Paterson",
    ageGroup: "KIDS",
    difficultyTier: 5,
    defaultWeeks: 2,
    keySignature: "Fa Mayor",
    timeSignature: "4/4",
    iconEmoji: "🚌",
    content: {
      clef: "grand",
      melody: ["F4", "F4", "F4", "F4", "A4", "F4", "C5", "C5"],
      melodyRhythm: [0.5, 0.5, 0.5, 0.5, 1, 1, 1, 1],
      bass: ["F3", "C3"],
      bassRhythm: [2, 2],
      chordsUsed: ["F", "C"],
      featuredNotes: ["F4", "A4", "C5", "G4"],
      lyricsHook: "The wheels on the bus go round and round",
    },
  },
  {
    title: "Little Miss Muffet",
    composer: "Tradicional",
    arranger: "Jim Paterson",
    ageGroup: "KIDS",
    difficultyTier: 6,
    defaultWeeks: 2,
    keySignature: "Fa Mayor",
    timeSignature: "6/8",
    iconEmoji: "🕷️",
    content: {
      clef: "grand",
      melody: ["F4", "G4", "A4", "A4", "G4", "F4"],
      melodyRhythm: [0.5, 0.5, 0.5, 0.5, 0.5, 1.5],
      bass: ["F3", "C3", "Bb3"],
      bassRhythm: [1.5, 1.5, 1.5],
      chordsUsed: ["F", "C", "Bb"],
      featuredNotes: ["F4", "G4", "A4", "C5", "Bb4"],
      lyricsHook: "Little Miss Muffet sat on a tuffet",
    },
  },
  {
    title: "We Wish You a Merry Christmas",
    composer: "Tradicional",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 7,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "3/4",
    seasonalTag: "christmas",
    iconEmoji: "🎄",
    content: {
      clef: "treble",
      melody: ["C4", "F4", "F4", "G4", "F4", "E4", "D4", "D4", "D4", "G4", "G4", "A4", "G4", "F4", "E4", "D4", "C4"],
      melodyRhythm: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4"],
      lyricsHook: "We wish you a merry Christmas, we wish you a merry Christmas",
    },
  },
  {
    title: "Jolly Old Saint Nicholas",
    composer: "Tradicional",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 8,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    seasonalTag: "christmas",
    iconEmoji: "🎅",
    content: {
      clef: "grand",
      melody: ["E4", "E4", "E4", "F4", "G4", "G4", "F4", "E4", "D4", "C4"],
      melodyRhythm: [1, 1, 1, 1, 2, 1, 1, 1, 1, 2],
      bass: ["C3", "C3"],
      bassRhythm: [4, 4],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4"],
      lyricsHook: "Jolly old Saint Nicholas, lean your ear this way!",
    },
  },
  {
    title: "Polly Put the Kettle On",
    composer: "Tradicional",
    arranger: "Jim Paterson",
    ageGroup: "KIDS",
    difficultyTier: 9,
    defaultWeeks: 2,
    keySignature: "Fa Mayor",
    timeSignature: "4/4",
    iconEmoji: "🫖",
    content: {
      clef: "grand",
      melody: ["C5", "C5", "C5", "A4", "Bb4", "C5"],
      melodyRhythm: [0.5, 0.5, 0.5, 0.5, 0.5, 1.5],
      bass: ["F3", "Bb3", "C3"],
      bassRhythm: [2, 2, 2],
      chordsUsed: ["F", "Bb", "C"],
      featuredNotes: ["C5", "A4", "Bb4", "F4", "G4"],
      lyricsHook: "Polly put the kettle on, we'll all have some tea",
    },
  },
  {
    title: "Rain Rain Go Away",
    composer: "Tradicional",
    arranger: "Regina Pratley",
    ageGroup: "KIDS",
    difficultyTier: 10,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🌧️",
    content: {
      clef: "treble",
      melody: ["E5", "D5", "C5", "E5", "D5", "C5"],
      melodyRhythm: [1, 1, 2, 1, 1, 2],
      featuredNotes: ["C5", "D5", "E5"],
      lyricsHook: "Rain, rain, go away, come again another day",
      isDuet: true,
    },
  },
  {
    title: "The Mulberry Bush",
    composer: "Tradicional",
    ageGroup: "KIDS",
    difficultyTier: 11,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🌳",
    content: {
      clef: "treble",
      melody: ["C4", "D4", "E4", "F4", "G4", "G4", "G4"],
      melodyRhythm: [0.5, 0.5, 0.5, 0.5, 1, 1, 1],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4"],
      lyricsHook: "Here we go round the mulberry bush",
      isDuet: true,
    },
  },
  {
    title: "Oh, When the Saints",
    composer: "Tradicional",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 12,
    defaultWeeks: 2,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🎺",
    content: {
      clef: "treble",
      melody: ["C4", "E4", "F4", "G4", "C4", "E4", "F4", "G4"],
      melodyRhythm: [1, 1, 1, 2, 1, 1, 1, 2],
      featuredNotes: ["C4", "E4", "F4", "G4"],
      lyricsHook: "Oh, when the saints go marching in",
    },
  },
  {
    title: "My Bonnie Lies Over the Ocean",
    composer: "Tradicional",
    arranger: "Gilbert DeBenedetti",
    ageGroup: "KIDS",
    difficultyTier: 13,
    defaultWeeks: 3,
    keySignature: "Do Mayor",
    timeSignature: "3/4",
    iconEmoji: "⛵",
    content: {
      clef: "treble",
      melody: ["E4", "F4", "G4", "G4", "F4", "E4", "G4", "A4", "G4"],
      melodyRhythm: [1, 1, 1, 1, 1, 1, 1, 1, 2],
      featuredNotes: ["E4", "F4", "G4", "A4"],
      lyricsHook: "My Bonnie lies over the ocean",
    },
  },
  {
    title: "Puff the Magic Dragon",
    composer: "Eric Moore",
    ageGroup: "KIDS",
    difficultyTier: 14,
    defaultWeeks: 3,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🐉",
    content: {
      clef: "grand",
      melody: ["G4", "A4", "G4", "E4", "D4", "E4", "F4", "G4"],
      melodyRhythm: [1, 0.5, 0.5, 1, 1, 1, 1, 2],
      bass: ["C3", "C3"],
      bassRhythm: [4, 4],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4"],
      lyricsHook: "Puff, the magic dragon, lived by the sea",
    },
  },
  {
    title: "Aloha Oe",
    composer: "Liliuokalani",
    arranger: "Regina Pratley",
    ageGroup: "KIDS",
    difficultyTier: 15,
    defaultWeeks: 3,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🌺",
    content: {
      clef: "grand",
      melody: ["E4", "G4", "C5", "A4", "G4", "F4", "E4", "D4"],
      melodyRhythm: [1, 1, 1.5, 0.5, 1, 1, 1, 2],
      bass: ["C3", "F3", "G3"],
      bassRhythm: [2, 1, 1],
      chordsUsed: ["C", "F", "G7"],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4", "C5"],
      lyricsHook: "Aloha oe, aloha oe, e ke onaona noho i ka lipo",
    },
  },
  {
    title: "Eso Que Tú Me Das",
    composer: "Jarabe de Palo",
    ageGroup: "KIDS",
    difficultyTier: 16,
    defaultWeeks: 3,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🎸",
    content: {
      clef: "treble",
      melody: ["E4", "D4", "C4", "E4", "D4", "D4", "E4", "D4", "C4", "C4"],
      melodyRhythm: [0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 1, 1],
      chordsUsed: ["C", "G", "Am", "F", "Dm"],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4", "A4"],
      lyricsHook: "Eso que tú me das",
    },
  },
  {
    title: "La Pantera Rosa",
    composer: "Henry Mancini",
    ageGroup: "KIDS",
    difficultyTier: 17,
    defaultWeeks: 3,
    keySignature: "Re Mayor",
    timeSignature: "4/4",
    iconEmoji: "🐆",
    content: {
      clef: "grand",
      melody: ["D4", "F4", "F#4", "G4", "G#4", "A4"],
      melodyRhythm: [1, 1, 1, 1, 1, 1],
      bass: ["D3"],
      bassRhythm: [6],
      featuredNotes: ["D4", "F4", "F#4", "G4", "G#4", "A4"],
    },
  },
  {
    title: "Popeye",
    composer: "Sammy Lerner",
    arranger: "A.C. Escobés",
    ageGroup: "KIDS",
    difficultyTier: 18,
    defaultWeeks: 3,
    keySignature: "Sol Mayor",
    timeSignature: "3/4",
    iconEmoji: "⚓",
    content: {
      clef: "grand",
      melody: ["D5", "D5", "D5", "B4", "D5", "G5"],
      melodyRhythm: [0.5, 0.5, 1, 0.5, 0.5, 1],
      bass: ["G3", "G3"],
      bassRhythm: [3, 3],
      chordsUsed: ["G"],
      featuredNotes: ["D5", "B4", "G5", "G4"],
      lyricsHook: "I'm Popeye the sailor man",
    },
  },
  {
    title: "El Submarino Amarillo",
    composer: "Lennon / McCartney",
    arranger: "A.C. Escobés",
    ageGroup: "KIDS",
    difficultyTier: 19,
    defaultWeeks: 3,
    keySignature: "Sol Mayor",
    timeSignature: "4/4",
    iconEmoji: "🟡",
    content: {
      clef: "grand",
      melody: ["D4", "D4", "D4", "D4", "E4", "D4", "C4", "D4"],
      melodyRhythm: [0.5, 0.5, 0.5, 0.5, 1, 1, 1.5, 0.5],
      bass: ["G3", "C3", "D3"],
      bassRhythm: [2, 1, 1],
      chordsUsed: ["G", "C", "D"],
      featuredNotes: ["D4", "E4", "C4", "G4"],
      lyricsHook: "We all live in a yellow submarine",
    },
  },
  {
    title: "Largo (Sinfonía n.5, del Nuevo Mundo)",
    composer: "A. Dvořák",
    arranger: "A.C. Escobés",
    ageGroup: "KIDS",
    difficultyTier: 20,
    defaultWeeks: 4,
    keySignature: "Do Mayor",
    timeSignature: "4/4",
    iconEmoji: "🏆",
    content: {
      clef: "grand",
      melody: ["E4", "E4", "F4", "G4", "E4", "D4", "C4"],
      melodyRhythm: [1.5, 0.5, 1, 2, 1.5, 0.5, 2],
      bass: ["C3", "A3", "F3"],
      bassRhythm: [3, 3, 3],
      featuredNotes: ["C4", "D4", "E4", "F4", "G4"],
      lyricsHook: "Goin' home, goin' home, I'm a-goin' home",
    },
  },
];
